import { channelGain } from './audio-bus';
let ctx:AudioContext|null=null;let ambientTimer:number|null=null;let ambientEnabled=false;
function audioContext(){if(!ctx)ctx=new AudioContext();if(ctx.state==='suspended')void ctx.resume();return ctx}
function tone(frequency:number,duration:number,type:OscillatorType='sine',gain=0.035,channel:'UI'|'RADIO'|'CALLS'|'VEHICLES'|'ALARMS'|'MUSIC'='UI'){const c=audioContext();const now=c.currentTime;const osc=c.createOscillator();const amp=c.createGain();osc.type=type;osc.frequency.setValueAtTime(frequency,now);const effective=Math.max(.00001,gain*channelGain(channel));amp.gain.setValueAtTime(.0001,now);amp.gain.exponentialRampToValueAtTime(Math.max(.0002,effective),now+0.015);amp.gain.exponentialRampToValueAtTime(.0001,now+duration);osc.connect(amp).connect(c.destination);osc.start(now);osc.stop(now+duration+0.03)}
export function playRadioPing(){tone(880,.08,'square',.025,'RADIO');window.setTimeout(()=>tone(660,.11,'square',.018,'RADIO'),90)}
export function playDispatchAlert(){tone(740,.12,'triangle',.035,'ALARMS');window.setTimeout(()=>tone(980,.18,'triangle',.035,'ALARMS'),140)}
export function play911Incoming(){tone(520,.16,'sine',.045,'CALLS');window.setTimeout(()=>tone(760,.16,'sine',.045,'CALLS'),190);window.setTimeout(()=>tone(520,.16,'sine',.045,'CALLS'),380)}
export function playMutualAid(){tone(420,.12,'square',.03,'RADIO');window.setTimeout(()=>tone(620,.16,'square',.03,'RADIO'),130);window.setTimeout(()=>tone(880,.2,'triangle',.035,'ALARMS'),300)}
export function playSiren(){const c=audioContext();const now=c.currentTime;const osc=c.createOscillator();const amp=c.createGain();osc.type='sawtooth';osc.frequency.setValueAtTime(520,now);osc.frequency.linearRampToValueAtTime(880,now+.42);osc.frequency.linearRampToValueAtTime(520,now+.84);amp.gain.setValueAtTime(.0001,now);amp.gain.exponentialRampToValueAtTime(Math.max(.0002,.045*channelGain('VEHICLES')),now+.04);amp.gain.exponentialRampToValueAtTime(.0001,now+.9);osc.connect(amp).connect(c.destination);osc.start(now);osc.stop(now+.95)}
export function playUiClick(){tone(920,.045,'sine',.015,'UI')}
export function playWarning(){tone(340,.12,'square',.028,'ALARMS');window.setTimeout(()=>tone(340,.12,'square',.028,'ALARMS'),180)}
export function playComplete(){tone(660,.09,'triangle',.025,'UI');window.setTimeout(()=>tone(990,.14,'triangle',.03,'UI'),100)}
export function toggleAmbient(){ambientEnabled=!ambientEnabled;if(!ambientEnabled){if(ambientTimer!==null)window.clearInterval(ambientTimer);ambientTimer=null;return false}const playAmbient=()=>{const c=audioContext();const now=c.currentTime;const osc=c.createOscillator();const gain=c.createGain();const filter=c.createBiquadFilter();osc.type='sine';osc.frequency.value=55;filter.type='lowpass';filter.frequency.value=180;gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(Math.max(.0002,.006*channelGain('MUSIC')),now+.3);gain.gain.exponentialRampToValueAtTime(.0001,now+2.4);osc.connect(filter).connect(gain).connect(c.destination);osc.start(now);osc.stop(now+2.5)};playAmbient();ambientTimer=window.setInterval(playAmbient,2200);return true}
export function isAmbientEnabled(){return ambientEnabled}
