import type { GameState, Hospital, Incident } from './state';

export type PatientSeverity='MINOR'|'MODERATE'|'SERIOUS'|'CRITICAL';
export type PatientStatus='WAITING'|'TREATED'|'TRANSPORTING'|'ADMITTED'|'DISCHARGED'|'DECEASED';
export interface Patient{id:string;incidentId:string;severity:PatientSeverity;condition:string;survival:number;transportRequired:boolean;requiresTrauma:boolean;requiresBurn:boolean;requiresPediatric:boolean;status:PatientStatus;hospitalId?:string;age:number;}

const clamp=(n:number,a=0,b=100)=>Math.max(a,Math.min(b,n));
const conditions=['Fraktur','Thoraxtrauma','Atemnot','Herz-Kreislauf-Problem','Verbrennung','Schnittverletzung','Intoxikation','Neurologischer Notfall'];
export function generatePatients(incident:Incident):Patient[]{const count=Math.max(0,incident.patients);return Array.from({length:count},(_,index)=>{const severity:PatientSeverity=index===0&&incident.priority===1?'CRITICAL':['MINOR','MODERATE','SERIOUS'][Math.floor(Math.random()*3)] as PatientSeverity;const trauma=incident.type==='TRAFFIC'||incident.type==='RAIL'||incident.type==='AVIATION'||incident.type==='MCI';const burn=incident.type==='FIRE'||incident.type==='WILDFIRE';return{id:`${incident.id}-PT-${index+1}`,incidentId:incident.id,severity,condition:conditions[Math.floor(Math.random()*conditions.length)],survival:clamp(severity==='CRITICAL'?55-incident.ageMinutes*4:severity==='SERIOUS'?78-incident.ageMinutes*2:94-incident.ageMinutes),transportRequired:true,requiresTrauma:trauma&&severity!=='MINOR',requiresBurn:burn&&severity==='SERIOUS',requiresPediatric:Math.random()<.16,status:'WAITING',age:1+Math.floor(Math.random()*92)};})}
export function chooseHospital(hospitals:Hospital[],patient:Patient){return hospitals.filter(h=>h.occupied<h.capacity).filter(h=>!patient.requiresTrauma||h.trauma).filter(h=>!patient.requiresBurn||h.burn).filter(h=>!patient.requiresPediatric||h.pediatric).sort((a,b)=>(a.occupied/a.capacity)-(b.occupied/b.capacity))[0]??null}
export function admit(hospital:Hospital,patient:Patient){if(hospital.occupied>=hospital.capacity)return{hospital,patient:{...patient,status:'WAITING' as const},accepted:false};return{hospital:{...hospital,occupied:hospital.occupied+1},patient:{...patient,status:'ADMITTED' as const,hospitalId:hospital.id},accepted:true}}
export function resolvePatient(patient:Patient,minutes:number){if(patient.status==='ADMITTED'||patient.status==='DISCHARGED')return patient;const loss=patient.severity==='CRITICAL'?minutes*.22:patient.severity==='SERIOUS'?minutes*.1:minutes*.02;const survival=clamp(patient.survival-loss);return{...patient,survival,status:survival<5?'DECEASED':patient.status}}
export function integrateHospitalCapacity(state:GameState,patients:Patient[]):GameState{const next=structuredClone(state);for(const p of patients){if(p.status!=='ADMITTED'||!p.hospitalId)continue;const h=next.hospitals.find(x=>x.id===p.hospitalId);if(h)h.occupied=Math.min(h.capacity,h.occupied)}return next}
