import type { IncidentDefinition } from './catalog';

export const EXTRA_INCIDENTS:IncidentDefinition[]=[
 {type:'MEDICAL',summary:'Herzstillstand in öffentlichem Gebäude',services:['EMS','FIRE'],weight:8,stages:['Herzstillstand gemeldet','CPR läuft','ALS eingetroffen','Transportentscheidung'],hazards:['MEDICAL'],patientRange:[1,1],escalation:42,regions:['DOWNTOWN','MALL','SCHOOLS'],objective:'Sofortige Reanimation und ALS-Versorgung.'},
 {type:'MEDICAL',summary:'Verdacht auf Überdosierung',services:['EMS','POLICE'],weight:7,stages:['Bewusstseinsstörung gemeldet','Substanz unbekannt','Atemweg gesichert','Transport'],hazards:['MEDICAL','HAZARD'],patientRange:[1,2],escalation:32,regions:['DOWNTOWN','SUBURBS','MOTEL'],objective:'Patient sichern, Exposition vermeiden und transportieren.'},
 {type:'FIRE',summary:'Fahrzeugbrand auf Tankstellenareal',services:['FIRE','EMS','POLICE'],weight:4,stages:['Fahrzeugbrand','Zapfsäulen gefährdet','Evakuierung','Gefahr gebannt'],hazards:['FIRE','FUEL'],patientRange:[0,5],escalation:58,regions:['HIGHWAY','MOTEL','DESERT'],objective:'Brandbegrenzung und Schutz der Tankstelleninfrastruktur.'},
 {type:'FIRE',summary:'Gasgeruch in Wohngebiet',services:['FIRE','POLICE'],weight:5,stages:['Gasgeruch gemeldet','Gebäude evakuiert','Leck lokalisiert','Gebäude freigegeben'],hazards:['GAS'],patientRange:[0,3],escalation:41,regions:['SUBURBS','DOWNTOWN'],objective:'Gasquelle isolieren und Bevölkerung schützen.'},
 {type:'FIRE',summary:'Gebäudeexplosion',services:['FIRE','EMS','POLICE'],weight:1,stages:['Explosion gemeldet','Sekundärgefahren','Verschüttete Personen','Stabilisierung'],hazards:['FIRE','EXPLOSION','STRUCTURAL'],patientRange:[2,16],escalation:80,regions:['INDUSTRIAL','DOWNTOWN'],objective:'Gefahrenbereich sichern und Rettung priorisieren.'},
 {type:'POLICE',summary:'Vermisste Person',services:['POLICE','EMS'],weight:7,stages:['Vermisst gemeldet','Suchgebiet festgelegt','Hinweis gefunden','Person gefunden'],hazards:[],patientRange:[0,1],escalation:15,regions:['FOREST','SUBURBS','PARK'],objective:'Suchraum organisieren und vermisste Person sicher finden.'},
 {type:'POLICE',summary:'Bewaffneter Raub in Geschäft',services:['POLICE'],weight:5,stages:['Raub gemeldet','Täterbeschreibung','Fluchtfahrzeug identifiziert','Tatverdächtiger gefasst'],hazards:['CRIME','WEAPON'],patientRange:[0,3],escalation:48,regions:['MALL','DOWNTOWN'],objective:'Gefahr eindämmen, Täterfahndung und medizinische Versorgung.'},
 {type:'ACTIVE_THREAT',summary:'Aktive Bedrohung in öffentlichem Gebäude',services:['POLICE','EMS'],weight:1,stages:['Notruf eingegangen','Perimeter','Taktischer Zugriff','Lage gesichert'],hazards:['ACTIVE_THREAT','WEAPON'],patientRange:[0,20],escalation:94,regions:['SCHOOLS','DOWNTOWN','MALL'],objective:'Zivilpersonen schützen und Bedrohung beenden.'},
 {type:'POLICE',summary:'Geiselnahme',services:['POLICE','EMS'],weight:1,stages:['Geiseln gemeldet','Verhandlung','Tactical Team bereit','Geiselnehmer neutralisiert'],hazards:['HOSTAGE','WEAPON'],patientRange:[0,12],escalation:90,regions:['DOWNTOWN','SUBURBS'],objective:'Geiseln sichern und taktische Lage kontrollieren.'},
 {type:'POLICE',summary:'Verfolgungsjagd auf Highway',services:['POLICE'],weight:4,stages:['Fahrzeugflucht','Highway Pursuit','Stop-Phase','Festnahme'],hazards:['PURSUIT','TRAFFIC'],patientRange:[0,2],escalation:50,regions:['HIGHWAY','DESERT'],objective:'Verfolgung kontrollieren und Kollateralschäden verhindern.'},
 {type:'TRAFFIC',summary:'LKW-Unfall mit Ladungsverlust',services:['POLICE','FIRE','EMS'],weight:6,stages:['LKW verunfallt','Ladung auf Fahrbahn','Stau entsteht','Fahrbahn geräumt'],hazards:['TRAFFIC'],patientRange:[1,6],escalation:46,regions:['HIGHWAY','INDUSTRIAL','PORT'],objective:'Unfallstelle sichern und Folgeunfälle verhindern.'},
 {type:'FLOOD',summary:'Flash Flood auf County Road',services:['FIRE','EMS','POLICE'],weight:2,stages:['Überflutung gemeldet','Straße unpassierbar','Fahrzeug eingeschlossen','Rettung abgeschlossen'],hazards:['FLOOD','WEATHER'],patientRange:[0,8],escalation:60,regions:['PINE_VALLEY','DESERT','HIGHWAY'],objective:'Überflutete Strecke sichern und eingeschlossene Personen retten.'},
 {type:'WEATHER',summary:'Tornado Warning mit Schäden',services:['POLICE','FIRE','EMS'],weight:1,stages:['Warnung aktiv','Erste Schäden','Verletzte gemeldet','Schadenslage stabil'],hazards:['WEATHER','STRUCTURAL'],patientRange:[2,25],escalation:88,regions:['SUBURBS','FARM','DESERT'],objective:'Schadenslage koordinieren und MCI vermeiden.'},
 {type:'MASS_FIRE',summary:'Mehrere Gebäude gleichzeitig in Brand',services:['FIRE','EMS','POLICE'],weight:.8,stages:['Mehrfachbrand gemeldet','Weitere Gebäude betroffen','Evakuierung läuft','Fire command etabliert'],hazards:['FIRE','WILDFIRE','STRUCTURAL'],patientRange:[2,30],escalation:86,regions:['DOWNTOWN','INDUSTRIAL','SUBURBS'],objective:'Mehrere Brandstellen parallel beherrschen.'},
 {type:'RAIL',summary:'Person unter Zug / Rail Emergency',services:['POLICE','FIRE','EMS'],weight:2,stages:['Rail incident','Strecke gesperrt','Rettung läuft','Rail operations restored'],hazards:['RAIL','MEDICAL'],patientRange:[1,5],escalation:55,regions:['RAIL','PORT'],objective:'Bahnverkehr sichern und Rettungszugang herstellen.'},
];
