import type { GameState, Incident, Service, UnitStatus, Weather, MapPoint } from './state';
import { CITIES, DIFFICULTY, INCIDENT_CATALOG, WEATHER_RULES, type Difficulty } from './catalog';
import { EXTRA_INCIDENTS } from './incidents-extra';
import { nextRoutePoint, routeProgress } from './routing';
import { dayPart, isWeekend, worldDemand } from './world';

export interface SimulationMetrics { responseScore:number; dispatchScore:number; resolutionScore:number; unitCoverage:number; callLoad:number; reputationDelta:number; }
const clamp=(n:number,a=0,b=100)=>Math.max(a,Math.min(b,n));
const weightedRandom=<T>(items:T[],weights:number[],rng:()=>number=Math.random)=>{const total=weights.reduce((a,b)=>a+b,0);let p=rng()*total;for(let i=0;i<items.length;i++){p-=weights[i];if(p<=0)return items[i]}return items[items.length-1]};
const moveToward=(from:MapPoint,to:MapPoint,distance:number)=>{const dx=to.x-from.x,dy=to.y-from.y,d=Math.hypot(dx,dy);if(d<=distance)return{point:{...to},reached:true};return{point:{x:from.x+dx/d*distance,y:from.y+dy/d*distance},reached:false}};
const callerNames=['Jamie Carter','Morgan Lee','Chris Parker','Avery Davis','Riley Wilson','Taylor Brown','Jordan Miller','Casey Johnson','Alex Garcia','Sam Thompson'];
const phoneArea=['555'];
function incidentConversation(defSummary:string,type:string){return[`911: "I need help with ${defSummary.toLowerCase()}."`,`DISPATCH: "What is your exact location?"`,`911: "I am at the reported address. Please send help."`,`DISPATCH: "Units are being dispatched now."`,`911: "I can see the responders arriving."`].map((line,index)=>`${index+1}. ${line}${type==='MEDICAL'&&index===1?' Caller confirms possible medical emergency.':''}`)}

export function advanceWorld(state:GameState,minutes:number,difficulty:Difficulty='NORMAL'):GameState{
 const next=structuredClone(state);const d=DIFFICULTY[difficulty];next.simulationMinutes+=minutes;next.serverTime=Date.now();const absolute=Math.floor(next.simulationMinutes);next.world.day=Math.floor(absolute/(24*60))+1;next.world.hour=Math.floor((absolute%(24*60))/60);next.world.minute=absolute%60;next.world.dayPart=dayPart(next.world.hour);next.world.isWeekend=isWeekend(next.world.day);
 const demand=worldDemand(next,difficulty);const part=next.world.dayPart;next.world.nightFactor=part==='NIGHT'?1:(part==='MORNING'||part==='EVENING'?.35:0);next.world.traffic=clamp(next.world.traffic+(part==='MORNING'?9:part==='EVENING'?12:part==='NIGHT'?-7:-2)*minutes*3,0,100);next.world.eventRate=clamp(demand.eventRate,0.1,5);
 for(const road of next.roads?.edges??[])road.traffic=clamp(next.world.traffic+(road.id.charCodeAt(road.id.length-1)%11-5),0,100);
 for(const u of next.units){
  if(u.status==='MAINTENANCE'){u.maintenance=clamp(u.maintenance+minutes*.18);u.fuel=clamp(u.fuel+minutes*.08);continue}
  if((u.status==='EN_ROUTE'||u.status==='RETURNING')&&u.route?.length){let index=u.routeIndex??0;let target=nextRoutePoint(u.route,index);while(target){const result=moveToward(u.position,target,(Math.max(.1,u.speed)/Math.max(.55,WEATHER_RULES[next.world.weather]?.traffic??1))*minutes/5);u.position=result.point;u.heading=Math.atan2(target.y-u.position.y,target.x-u.position.x);if(!result.reached)break;index++;target=nextRoutePoint(u.route,index);if(index>=u.route.length-1)break}u.routeIndex=index;if(u.status==='EN_ROUTE'&&routeProgress(u.route,index)>=1){u.position={...u.target??u.position};u.status='ON_SCENE';u.routeIndex=0}else if(u.status==='RETURNING'&&routeProgress(u.route,index)>=1){u.position={...u.target??u.position};u.status='AVAILABLE';u.target=undefined;u.route=undefined;u.routeIndex=0}}
  else if((u.status==='EN_ROUTE'||u.status==='RETURNING')&&u.target){const result=moveToward(u.position,u.target,(Math.max(.1,u.speed)/Math.max(.55,WEATHER_RULES[next.world.weather]?.traffic??1))*minutes/5);u.position=result.point;if(result.reached){if(u.status==='EN_ROUTE')u.status='ON_SCENE';else{u.status='AVAILABLE';u.target=undefined}}}
  if(u.status!=='AVAILABLE'){u.fuel=clamp(u.fuel-minutes*(u.service==='FIRE'?.032:.02));u.maintenance=clamp(u.maintenance-minutes*.025);u.mileage=(u.mileage??0)+Math.max(0,u.speed*minutes*.15)}
  if(u.fuel<10||u.maintenance<12)u.status='OUT_OF_SERVICE';
 }
 for(const i of next.incidents){if(['COMPLETE','CANCELLED'].includes(i.status))continue;i.ageMinutes+=minutes;if(i.stageIndex<i.stages.length-1){const threshold=4+i.priority*2;if(i.ageMinutes>threshold*(i.stageIndex+1)){i.stageIndex++;i.summary=i.stages[i.stageIndex];i.danger=clamp(i.danger+i.escalation*.04);if(i.priority===1)i.danger=clamp(i.danger+1);if(i.conversation)i.conversation=[...i.conversation,`${i.stageIndex+1}. Caller update: ${i.summary}`]}}if(i.status==='RESPONDING'&&i.unitIds.some(id=>next.units.find(u=>u.id===id)?.status==='ON_SCENE'))i.status='ON_SCENE';if(i.status==='ON_SCENE'&&i.ageMinutes>8+i.priority*2)i.status='ACTIVE';if(i.status==='ACTIVE'&&i.stageIndex>=i.stages.length-1&&i.unitIds.every(id=>['ON_SCENE','RETURNING','AVAILABLE','OUT_OF_SERVICE','MAINTENANCE'].includes(next.units.find(u=>u.id===id)?.status??'')))i.status='STABILIZED'}
 return next;
}
function weatherTrafficFactor(weather:Weather){return WEATHER_RULES[weather]?.traffic??1}
export function generateIncident(state:GameState,difficulty:Difficulty='NORMAL',rng:()=>number=Math.random):Incident{
 const all=[...INCIDENT_CATALOG,...EXTRA_INCIDENTS];const weighted=all.map(def=>{let w=def.weight;const part=dayPart(state.world.hour);if(part==='NIGHT')w*=def.type==='POLICE'||def.type==='MEDICAL'||def.type==='ACTIVE_THREAT'?1.35:.9;if(state.world.traffic>70&&def.type==='TRAFFIC')w*=1.7;const weather=WEATHER_RULES[state.world.weather];if(def.type==='WILDFIRE'||def.type==='FIRE'||def.type==='MASS_FIRE')w*=weather.fire;if(def.type==='MEDICAL')w*=weather.medical;if(def.type==='FLOOD'&&(state.world.weather==='FLOODING'||state.world.weather==='HEAVY_RAIN'))w*=3;if(def.type==='WEATHER'&&['THUNDERSTORM','WINDSTORM','TORNADO'].includes(state.world.weather))w*=4;return Math.max(.01,w*DIFFICULTY[difficulty].eventRate)});
 const def=weightedRandom(all,weighted,rng);const city=CITIES[Math.floor(rng()*CITIES.length)];const region=def.regions[Math.floor(rng()*def.regions.length)];const priority=(def.type==='MCI'||def.type==='AVIATION'||def.type==='RAIL'||def.type==='ACTIVE_THREAT'||def.type==='WEATHER'?1:1+Math.floor(rng()*3)) as 1|2|3|4;const patients=Math.floor(def.patientRange[0]+rng()*(def.patientRange[1]-def.patientRange[0]+1));const seq=String(state.statistics.calls+state.incidents.length+1).padStart(3,'0');const caller=callerNames[Math.floor(rng()*callerNames.length)];const phone=`(${phoneArea[0]}) 010-${String(1000+Math.floor(rng()*8999))}`;
 return{id:`CALL-${seq}`,type:def.type,priority,location:{x:8+rng()*84,y:8+rng()*84},address:`${100+Math.floor(rng()*8900)} ${['Pine Street','Market Avenue','Canyon Road','Harbor Drive','8th Avenue','Redwood Boulevard'][Math.floor(rng()*6)]}, ${city.name}, RS`,status:'NEW',summary:def.summary,description:`${def.summary}. Region ${region}. 911 Caller liefert fortlaufend neue Informationen.`,callerName:caller,callerPhone:phone,conversation:incidentConversation(def.summary,def.type),hazards:[...def.hazards],createdAt:Date.now(),ageMinutes:0,stageIndex:0,stages:def.stages,requiredServices:[...def.services] as Service[],unitIds:[],patients,escalation:def.escalation*DIFFICULTY[difficulty].escalation,danger:def.hazards.length*18+priority*8,objective:def.objective,sections:def.type==='MCI'||def.type==='AVIATION'?[{id:'TRIAGE',name:'Triage',objective:'Patienten priorisieren',unitIds:[]},{id:'TRANSPORT',name:'Transport',objective:'Krankenhäuser zuweisen',unitIds:[]}]:undefined};
}
export function calculateDispatchMetrics(state:GameState):SimulationMetrics{const active=state.incidents.filter(i=>!['COMPLETE','CANCELLED'].includes(i.status));const covered=active.filter(i=>i.unitIds.length>0).length;const response=active.length?active.reduce((s,i)=>s+clamp(100-i.ageMinutes*3-i.danger*.15),0)/active.length:100;const capacity=state.units.length?clamp(state.units.filter(u=>u.status==='AVAILABLE').length/state.units.length*100):0;const load=state.world.eventRate*(1+active.length/12);const dispatch=clamp(capacity*.7+response*.3);const resolution=state.statistics.completed?clamp((state.statistics.firesControlled+state.statistics.arrests+state.statistics.patientsSaved)/Math.max(1,state.statistics.completed)*25):72;const score=clamp((response+dispatch+resolution+capacity)/4);return{responseScore:response,dispatchScore:dispatch,resolutionScore:resolution,unitCoverage:active.length?covered/active.length*100:100,callLoad:load,reputationDelta:(score-70)/100}}
export function transitionUnitStatus(current:UnitStatus,action:'DISPATCH'|'ARRIVE'|'COMPLETE'|'RETURN'|'MAINTENANCE'):UnitStatus{if(action==='DISPATCH'&&current==='AVAILABLE')return'EN_ROUTE';if(action==='ARRIVE'&&current==='EN_ROUTE')return'ON_SCENE';if(action==='COMPLETE'&&['ON_SCENE','TRANSPORTING','BUSY'].includes(current))return'RETURNING';if(action==='RETURN'&&current==='RETURNING')return'AVAILABLE';if(action==='MAINTENANCE'&&current!=='EN_ROUTE')return'MAINTENANCE';return current}
