export type Service='POLICE'|'FIRE'|'EMS';
export type UnitStatus='AVAILABLE'|'BUSY'|'EN_ROUTE'|'ON_SCENE'|'TRANSPORTING'|'RETURNING'|'OUT_OF_SERVICE'|'MAINTENANCE';
export type IncidentStatus='NEW'|'DISPATCHING'|'RESPONDING'|'ON_SCENE'|'ACTIVE'|'STABILIZED'|'TRANSPORT'|'COMPLETE'|'CANCELLED';
export type IncidentType='MEDICAL'|'FIRE'|'POLICE'|'TRAFFIC'|'HAZMAT'|'WILDFIRE'|'WEATHER'|'AVIATION'|'RAIL'|'MCI'|'FLOOD'|'MASS_FIRE'|'ACTIVE_THREAT';
export type Role='PLAYER';
export type Weather='CLEAR'|'CLOUDY'|'RAIN'|'HEAVY_RAIN'|'THUNDERSTORM'|'FOG'|'SNOW'|'HEATWAVE'|'WINDSTORM'|'FLOODING';
export type FacilityType='POLICE_STATION'|'FIRE_STATION'|'EMS_STATION'|'HOSPITAL'|'SCHOOL'|'FUEL'|'SHOPPING'|'INDUSTRIAL'|'AIRPORT'|'RAIL'|'PARK'|'BRIDGE';
export type Shift='MORNING'|'AFTERNOON'|'NIGHT';
export type PatientSeverity='MINOR'|'MODERATE'|'SERIOUS'|'CRITICAL';
export type PatientStatus='WAITING'|'TREATED'|'TRANSPORTING'|'ADMITTED'|'DISCHARGED'|'DECEASED';
export interface MapPoint{x:number;y:number}
export interface RoadNode{id:string;position:MapPoint;signal?:boolean}
export interface RoadEdge{id:string;from:string;to:string;lanes:number;speedLimit:number;traffic:number;blocked?:boolean;highway?:boolean}
export interface Facility{id:string;name:string;type:FacilityType;position:MapPoint;district:string;capacity?:number;ownerId?:string;ownerName?:string;level?:number;upgrades?:string[]}
export interface Unit{id:string;callsign:string;service:Service;type:string;status:UnitStatus;position:MapPoint;target?:MapPoint;route?:MapPoint[];routeIndex?:number;heading?:number;speed:number;crew:number;capabilities:string[];maintenance:number;fuel:number;assignedIncidentId?:string;vehicleModel?:string;lightPattern?:'STEADY'|'DUAL'|'TRIPLE';ownerId?:string;ownerName?:string}
export interface Incident{id:string;type:IncidentType;priority:1|2|3|4;location:MapPoint;address:string;status:IncidentStatus;summary:string;description?:string;createdAt:number;ageMinutes:number;stageIndex:number;stages:string[];requiredServices:Service[];unitIds:string[];patients:number;escalation:number;danger:number;objective:string;ownerId?:string;ownerName?:string;commandPost?:MapPoint;incidentCommander?:string;sections?:Array<{id:string;name:string;objective:string;unitIds:string[]}>}
export interface Personnel{id:string;name:string;role:Role;experience:number;stress:number;salary:number;performance:number;errorRate:number;shift:Shift;active:boolean;certifications?:string[];training?:number;fatigue?:number;overtimeHours?:number;ownerId?:string;}
export interface Patient{id:string;incidentId:string;severity:PatientSeverity;condition:string;survival:number;transportRequired:boolean;requiresTrauma:boolean;requiresBurn:boolean;requiresPediatric:boolean;status:PatientStatus;hospitalId?:string;age:number;}
export interface Hospital{id:string;name:string;capacity:number;occupied:number;trauma:boolean;burn:boolean;pediatric:boolean;helipad:boolean}
export interface Finance{revenueToday:number;costsToday:number;monthlyFunding:number;maintenance:number;payroll:number;fuel:number;upgrades:number;emergencyReserve?:number;fleetValue?:number}
export interface NewsItem{id:string;headline:string;body:string;severity:'INFO'|'POSITIVE'|'NEGATIVE'|'CRITICAL';timestamp:number;impact:number;tags:string[];}
export interface WorldState{population:number;weather:Weather;traffic:number;day:number;hour:number;minute:number;eventRate:number;powerLoad:number;nightFactor?:number;emergencyLevel?:number;isWeekend?:boolean;dayPart?:'NIGHT'|'MORNING'|'DAY'|'EVENING'}
export interface LobbyState{id:string;name:string;hostId:string;players:Array<{id:string;name:string;role:Role;ready:boolean;connected?:boolean}>;maxPlayers:number}
export interface GameState{version:2;serverTime:number;simulationMinutes:number;center:{id:string;name:string;money:number;reputation:number;level:number;region:string};units:Unit[];incidents:Incident[];personnel:Personnel[];patients?:Patient[];hospitals:Hospital[];finance:Finance;world:WorldState;roads?:{nodes:RoadNode[];edges:RoadEdge[]};facilities:Facility[];selectedIncidentId?:string;eventLog:string[];news?:NewsItem[];statistics:{calls:number;completed:number;patientsSaved:number;firesControlled:number;arrests:number;falseAlarms:number;averageResponse:number;majorIncidents?:number;milesDriven?:number;trainingHours?:number}}
const nodes:RoadNode[]=[];for(let r=0;r<7;r++)for(let c=0;c<9;c++)nodes.push({id:`N${r*9+c+1}`,position:{x:7+c*10.7,y:7+r*14},signal:(r+c)%4===0});
const edges:RoadEdge[]=[];let ei=1;for(let r=0;r<7;r++)for(let c=0;c<8;c++){const a=r*9+c+1,b=a+1;const highway=c%3===0;edges.push({id:`E${ei++}`,from:`N${a}`,to:`N${b}`,lanes:highway?3:2,speedLimit:highway?50:35,traffic:30,highway});edges.push({id:`E${ei++}`,from:`N${b}`,to:`N${a}`,lanes:highway?3:2,speedLimit:highway?50:35,traffic:30,highway})}for(let r=0;r<6;r++)for(let c=0;c<9;c++){const a=r*9+c+1,b=a+9;edges.push({id:`E${ei++}`,from:`N${a}`,to:`N${b}`,lanes:2,speedLimit:35,traffic:30});edges.push({id:`E${ei++}`,from:`N${b}`,to:`N${a}`,lanes:2,speedLimit:35,traffic:30})}
export const facilities:Facility[]=[{id:'F-01',name:'Redwood Memorial Hospital',type:'HOSPITAL',position:{x:70,y:28},district:'Central',capacity:80},{id:'F-02',name:'Lakewood General Hospital',type:'HOSPITAL',position:{x:34,y:82},district:'Lakewood',capacity:55},{id:'F-03',name:'Redwood International Airport',type:'AIRPORT',position:{x:86,y:12},district:'North'},{id:'F-04',name:'Union Station',type:'RAIL',position:{x:82,y:56},district:'Port Redwood'},{id:'F-05',name:'Canyon View High School',type:'SCHOOL',position:{x:55,y:34},district:'Pine Valley'},{id:'F-06',name:'Redwood Mall',type:'SHOPPING',position:{x:62,y:70},district:'Eastside'},{id:'F-07',name:'Port Redwood Industrial Park',type:'INDUSTRIAL',position:{x:83,y:46},district:'Port Redwood'},{id:'F-08',name:'Cedar Creek Park',type:'PARK',position:{x:20,y:35},district:'Westside'},{id:'F-09',name:'Redwood River Bridge',type:'BRIDGE',position:{x:49,y:58},district:'Central'}];
export const initialGameState:GameState={version:2,serverTime:Date.now(),simulationMinutes:8*60+42,center:{id:'dcc-001',name:'Redwood Metro 911',money:250000,reputation:72,level:1,region:'Redwood Metro County'},units:[],incidents:[],personnel:[],patients:[],hospitals:[{id:'HOSP-01',name:'Redwood Memorial Hospital',capacity:80,occupied:54,trauma:true,burn:true,pediatric:true,helipad:true},{id:'HOSP-02',name:'Lakewood General',capacity:55,occupied:31,trauma:false,burn:false,pediatric:true,helipad:false},{id:'HOSP-03',name:'Port Redwood Medical Center',capacity:40,occupied:29,trauma:true,burn:false,pediatric:false,helipad:true}],finance:{revenueToday:0,costsToday:0,monthlyFunding:76000,maintenance:0,payroll:0,fuel:0,upgrades:0,emergencyReserve:90000,fleetValue:0},world:{population:128400,weather:'CLEAR',traffic:47,day:1,hour:8,minute:42,eventRate:1,powerLoad:38,nightFactor:0,emergencyLevel:1,isWeekend:false,dayPart:'MORNING'},roads:{nodes,edges},facilities,news:[],statistics:{calls:0,completed:0,patientsSaved:0,firesControlled:0,arrests:0,falseAlarms:0,averageResponse:0,majorIncidents:0,milesDriven:0,trainingHours:0},eventLog:[]};
export const cloneState=():GameState=>structuredClone(initialGameState);
export const formatClock=(m:number)=>`${String(Math.floor(m/60)%24).padStart(2,'0')}:${String(Math.floor(m%60)).padStart(2,'0')}`;
export const getUnitStatusLabel=(s:UnitStatus)=>({AVAILABLE:'VERFÜGBAR',BUSY:'BESETZT',EN_ROUTE:'ANFAHRT',ON_SCENE:'VOR ORT',TRANSPORTING:'TRANSPORT',RETURNING:'RÜCKKEHR',OUT_OF_SERVICE:'AUßER DIENST',MAINTENANCE:'WARTUNG'}[s]);
export const getIncidentStatusLabel=(s:IncidentStatus)=>({NEW:'NEUER NOTRUF',DISPATCHING:'IN BEARBEITUNG',RESPONDING:'KRÄFTE UNTERWEGS',ON_SCENE:'VOR ORT',ACTIVE:'AKTIV',STABILIZED:'STABILISIERT',TRANSPORT:'TRANSPORT',COMPLETE:'ABGESCHLOSSEN',CANCELLED:'ABGEBROCHEN'}[s]);
export const weatherLabel=(w:Weather)=>({CLEAR:'Klar',CLOUDY:'Bewölkt',RAIN:'Regen',HEAVY_RAIN:'Starkregen',THUNDERSTORM:'Gewitter',FOG:'Nebel',SNOW:'Schnee',HEATWAVE:'Hitzewelle',WINDSTORM:'Sturm',FLOODING:'Überschwemmung'}[w]);
