export const de={
 app:{title:'American Dispatch',subtitle:'Emergency Communications Simulator'},
 nav:{cad:'CAD',agency:'Leitstelle',ranks:'Ränge',world:'Welt',personnel:'Personal',hospitals:'Krankenhäuser',reports:'Berichte',settings:'Einstellungen',admin:'Administration'},
 actions:{newGame:'Neues Spiel',multiplayer:'Multiplayer',load:'Spiel laden',save:'Spiel speichern',settings:'Einstellungen',credits:'Credits',accept:'Notruf annehmen',dispatch:'Alarmieren',complete:'Abschließen',cancel:'Abbrechen',mutualAid:'Amtshilfe anfordern',build:'Bauen',upgrade:'Ausbauen',hire:'Einstellen',train:'Ausbilden',repair:'Warten',transport:'Transportieren',select:'Auswählen',kick:'Entfernen',role:'Rolle vergeben',spawn:'Einsatz erzeugen'},
 status:{available:'Verfügbar',busy:'Belegt',responding:'Auf Anfahrt',enRoute:'Anfahrt',onScene:'Vor Ort',transport:'Transport',returning:'Rückkehr',outOfService:'Außer Dienst',maintenance:'Wartung',online:'Online',offline:'Offline'},
 incident:{incoming:'Eingehender 911-Notruf',priority:'Priorität',hazards:'Gefahren',patients:'Patienten',objective:'Einsatzziel',timeline:'Verlauf',escalation:'Eskalation',danger:'Gefahrenstufe',required:'Benötigte Dienste',address:'Adresse',age:'Dauer'},
 world:{weather:'Wetter',traffic:'Verkehr',day:'Tag',time:'Uhrzeit',population:'Bevölkerung',weekend:'Wochenende',morning:'Morgen',dayPart:'Tageszeit',emergency:'Notstandsstufe',power:'Netzlast'},
 finance:{budget:'Budget',revenue:'Einnahmen',costs:'Ausgaben',payroll:'Personal',maintenance:'Wartung',fuel:'Treibstoff',upgrades:'Ausbauten',reserve:'Reserve',net:'Netto',contracts:'Verträge'},
 roles:{callTaker:'911 Call Taker',police:'Police Dispatcher',fire:'Fire Dispatcher',ems:'EMS Dispatcher',supervisor:'Supervisor',manager:'Manager',admin:'Administrator'},
 labels:{onlineCad:'CAD ONLINE',redwood:'REDWOOD METRO · USA',calls:'911 NOTRUFE',units:'EINHEITEN',news:'PRESSE & ÖFFENTLICHKEIT',districts:'REGIONEN',performance:'LEISTUNG',reputation:'REPUTATION',xp:'ERFAHRUNG',level:'LEVEL',lobby:'LOBBY',players:'SPIELER',shift:'SCHICHT',stress:'STRESS',fatigue:'ERSCHÖPFUNG',salary:'GEHALT',training:'AUSBILDUNG',hospitalCapacity:'KAPAZITÄT',occupied:'BELEGT',contractsAvailable:'VERFÜGBARE VERTRÄGE',simulation:'SIMULATION',debug:'DEBUG'},
 messages:{waiting:'Warte auf einen neuen 911-Notruf …',reconnecting:'Verbindung zur Leitstelle wird wiederhergestellt …',noUnits:'Keine eigene Einheit verfügbar.',noPlayers:'Keine andere Leitstelle verfügbar.',saved:'Spielstand gespeichert.',loaded:'Spielstand geladen.',savedLocal:'Lokales Profil gespeichert.',buildMode:'BAUMODUS AKTIV · Linksklick auf die Karte · ESC zum Abbrechen'},
 weather:{CLEAR:'Klar',CLOUDY:'Bewölkt',RAIN:'Regen',HEAVY_RAIN:'Starkregen',THUNDERSTORM:'Gewitter',FOG:'Nebel',SNOW:'Schnee',HEATWAVE:'Hitzewelle',WINDSTORM:'Sturm',FLOODING:'Überschwemmung'},
} as const;
