export const en={
 app:{title:'American Dispatch',subtitle:'Emergency Communications Simulator'},
 nav:{cad:'CAD',agency:'Agency',ranks:'Ranks',world:'World',personnel:'Personnel',hospitals:'Hospitals',reports:'Reports',settings:'Settings',admin:'Administration'},
 actions:{newGame:'New Game',multiplayer:'Multiplayer',load:'Load Game',save:'Save Game',settings:'Settings',credits:'Credits',accept:'Accept Call',dispatch:'Dispatch',complete:'Complete',cancel:'Cancel',mutualAid:'Request Mutual Aid',build:'Build',upgrade:'Upgrade',hire:'Hire',train:'Train',repair:'Service',transport:'Transport',select:'Select',kick:'Remove',role:'Assign Role',spawn:'Spawn Incident'},
 status:{available:'Available',busy:'Busy',responding:'Responding',enRoute:'En Route',onScene:'On Scene',transport:'Transporting',returning:'Returning',outOfService:'Out of Service',maintenance:'Maintenance',online:'Online',offline:'Offline'},
 incident:{incoming:'Incoming 911',priority:'Priority',hazards:'Hazards',patients:'Patients',objective:'Objective',timeline:'Timeline',escalation:'Escalation',danger:'Danger',required:'Required Services',address:'Address',age:'Age'},
 world:{weather:'Weather',traffic:'Traffic',day:'Day',time:'Time',population:'Population',weekend:'Weekend',morning:'Morning',dayPart:'Day Part',emergency:'Emergency Level',power:'Power Load'},
 finance:{budget:'Budget',revenue:'Revenue',costs:'Costs',payroll:'Payroll',maintenance:'Maintenance',fuel:'Fuel',upgrades:'Upgrades',reserve:'Reserve',net:'Net',contracts:'Contracts'},
 roles:{callTaker:'911 Call Taker',police:'Police Dispatcher',fire:'Fire Dispatcher',ems:'EMS Dispatcher',supervisor:'Supervisor',manager:'Manager',admin:'Administrator'},
 labels:{onlineCad:'CAD ONLINE',redwood:'REDWOOD METRO · USA',calls:'911 CALLS',units:'UNITS',news:'PRESS & PUBLIC',districts:'REGIONS',performance:'PERFORMANCE',reputation:'REPUTATION',xp:'EXPERIENCE',level:'LEVEL',lobby:'LOBBY',players:'PLAYERS',shift:'SHIFT',stress:'STRESS',fatigue:'FATIGUE',salary:'SALARY',training:'TRAINING',hospitalCapacity:'CAPACITY',occupied:'OCCUPIED',contractsAvailable:'AVAILABLE CONTRACTS',simulation:'SIMULATION',debug:'DEBUG'},
 messages:{waiting:'Waiting for a new 911 call …',reconnecting:'Reconnecting to dispatch server …',noUnits:'No owned unit available.',noPlayers:'No other dispatch center available.',saved:'Game saved.',loaded:'Game loaded.',savedLocal:'Local profile saved.',buildMode:'BUILD MODE ACTIVE · Left click the map · ESC to cancel'},
 weather:{CLEAR:'Clear',CLOUDY:'Cloudy',RAIN:'Rain',HEAVY_RAIN:'Heavy Rain',THUNDERSTORM:'Thunderstorm',FOG:'Fog',SNOW:'Snow',HEATWAVE:'Heatwave',WINDSTORM:'Windstorm',FLOODING:'Flooding'},
} as const;
