import { useEffect, useState } from 'react';
import type { GameState } from '../game/state';

type LobbyMeta={id:string;name:string;joinCode?:string;private:boolean;players:number;maxPlayers:number;difficulty:string};
type Props={state:GameState;playerId:string;send:(message:unknown)=>boolean;notice:(message:string)=>void};

export function LobbyPanel({state,playerId,send,notice}:Props){
 const current=(state as any).__lobby as (LobbyMeta&{hostId?:string;players:Array<{id:string;name:string;role:string;ready:boolean}>})|undefined;
 const [lobbies,setLobbies]=useState<LobbyMeta[]>([]);const [name,setName]=useState('Redwood Metro Coop');const [privateLobby,setPrivateLobby]=useState(false);const [password,setPassword]=useState('');const [difficulty,setDifficulty]=useState('NORMAL');const [joinCode,setJoinCode]=useState('');const [joinPassword,setJoinPassword]=useState('');
 const refresh=():void=>{void fetch('/api/lobbies',{cache:'no-store'}).then(r=>r.ok?r.json():[]).then(x=>setLobbies(Array.isArray(x)?x:[])).catch(()=>setLobbies([]))};
 useEffect(()=>{refresh();const id=window.setInterval(refresh,5000);return()=>window.clearInterval(id)},[]);
 return <div className="ops-page lobby-page"><header className="ops-hero"><small>MULTIPLAYER OPERATIONS</small><h2>Lobby Center</h2><p>Erstelle oder betrete eine getrennte Redwood-Spielinstanz. Jede Lobby besitzt ihren eigenen Spielstand, Host und Simulationszustand.</p></header>
  <div className="ops-grid two">
   <article className="ops-card"><small>AKTUELLE SITZUNG</small><h3>{current?.name??'Keine Sitzung'}</h3><div className="stat-line"><span>Lobby-ID</span><b>{current?.id??'—'}</b></div><div className="stat-line"><span>Spieler</span><b>{current?.players?.length??0} / {current?.maxPlayers??16}</b></div><div className="stat-line"><span>Schwierigkeit</span><b>{current?.difficulty??'NORMAL'}</b></div><div className="stat-line"><span>Join-Code</span><b>{current?.joinCode??'—'}</b></div><div className="player-list">{current?.players?.map(p=><div className="player-row" key={p.id}><b>{p.name}</b><span>{p.role}</span>{p.id===current?.hostId&&<small>HOST</small>}</div>)}</div><div className="ops-actions"><button onClick={()=>{send({type:'LEAVE_LOBBY'});notice('Öffentliche Lobby wird geöffnet.')}} disabled={current?.id==='PUBLIC-REDWOOD'}>LOBBY VERLASSEN</button></div></article>
   <article className="ops-card"><small>LOBBY ERSTELLEN</small><label>Name<input value={name} maxLength={32} onChange={e=>setName(e.target.value)}/></label><label>Schwierigkeit<select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option>RELAXED</option><option>NORMAL</option><option>HARD</option><option>REALISTIC</option></select></label><label className="checkline"><input type="checkbox" checked={privateLobby} onChange={e=>setPrivateLobby(e.target.checked)}/> Private Lobby</label>{privateLobby&&<label>Passwort<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>}<button className="hero-button" onClick={()=>{if(!name.trim())return notice('Bitte einen Lobby-Namen eingeben.');if(privateLobby&&!password)return notice('Private Lobby benötigt ein Passwort.');send({type:'CREATE_LOBBY',name:name.trim(),private:privateLobby,password,difficulty,maxPlayers:16});notice('Lobby wird erstellt …')}}>SITZUNG ERSTELLEN</button></article>
  </div>
  <article className="ops-card wide"><small>VERFÜGBARE LOBBIES</small><div className="join-tools"><input placeholder="Lobby-ID oder Name" value={joinCode} onChange={e=>setJoinCode(e.target.value)}/><input type="password" placeholder="Passwort (private)" value={joinPassword} onChange={e=>setJoinPassword(e.target.value)}/><button onClick={()=>{const target=lobbies.find(x=>x.id===joinCode||x.name.toLowerCase()===joinCode.toLowerCase()||x.joinCode===joinCode.toUpperCase());if(!target)return notice('Keine passende Lobby gefunden.');if(target.private&&!joinPassword)return notice('Private Lobby benötigt ein Passwort.');send({type:'JOIN_LOBBY',lobbyId:target.id,password:joinPassword});notice(`Beitritt zu ${target.name} …`);}}>BEITRETEN</button><button onClick={refresh}>AKTUALISIEREN</button></div><div className="contract-list">{lobbies.map(l=><div key={l.id}><div><b>{l.name}</b><span>{l.private?'PRIVAT':'ÖFFENTLICH'} · {l.difficulty}</span></div><span>{l.players} / {l.maxPlayers}</span><span>{l.private?'PRIVAT':(l.joinCode??l.id)}</span><button disabled={l.players>=l.maxPlayers||l.id===current?.id} onClick={()=>{if(l.private&&!joinPassword)return notice('Passwort für private Lobby eingeben.');send({type:'JOIN_LOBBY',lobbyId:l.id,password:joinPassword});notice(`Beitritt zu ${l.name} …`)}}>BEITRETEN</button></div>)}</div></article>
 </div>
}
