import { useMemo, useState } from 'react';
import type { GameState, Service } from '../game/state';
import { getAudioSettings, setAudioChannel, type AudioChannel } from '../game/audio-bus';
import { CONTRACTS } from '../game/contracts';
import { CITIES } from '../game/catalog';
import { progressionTitle, levelInfo, xpForNextLevel } from '../game/progression';
import { weatherLabel } from '../game/state';

export type OpsTab='AGENCY'|'PERSONNEL'|'HOSPITALS'|'WORLD'|'REPORTS'|'SETTINGS'|'ADMIN'|'RANKS';
const services:Service[]=['POLICE','FIRE','EMS'];
const roles=['CALL_TAKER','POLICE_DISPATCHER','FIRE_DISPATCHER','EMS_DISPATCHER','SUPERVISOR','MANAGER','ADMINISTRATOR'] as const;
const upgradeCosts:Record<string,number>={FLEET:35000,STAFF:25000,CELLS:30000,APPARATUS:45000,MEDICAL:40000,STORAGE:20000};
const channelLabels:Record<AudioChannel,string>={MASTER:'Master',UI:'Interface',RADIO:'Funk',CALLS:'Notrufe',VEHICLES:'Fahrzeuge',ALARMS:'Alarme',MUSIC:'Musik'};

type Props={tab:OpsTab;setTab:(t:OpsTab)=>void;state:GameState;profile:any;playerId:string;connected:boolean;send:(message:unknown)=>boolean;notice:(message:string)=>void;};
const money=(v:number)=>`$${Math.max(0,Math.round(v)).toLocaleString('en-US')}`;

export function OperationsDashboard({tab,setTab,state,profile,playerId,connected,send,notice}:Props){
 const [name,setName]=useState(profile.playerName??'Dispatcher');
 const [difficulty,setDifficulty]=useState(profile.difficulty??'NORMAL');
 const [audio,setAudio]=useState(getAudioSettings());
 const players=((state as any).__lobby?.players??[]) as Array<{id:string;name:string;role:string;ready:boolean;connected:boolean}>;
 const ownUnits=state.units.filter(u=>u.ownerId===playerId); const ownFacilities=state.facilities.filter(f=>f.ownerId===playerId); const ownStaff=state.personnel.filter(p=>p.ownerId===playerId);
 const ownIncidents=state.incidents.filter(i=>i.ownerId===playerId); const active=ownIncidents.filter(i=>!['COMPLETE','CANCELLED'].includes(i.status));
 const performance=useMemo(()=>{const calls=Math.max(1,ownIncidents.length);const completed=ownIncidents.filter(i=>i.status==='COMPLETE').length;return Math.round((completed/calls)*70+Math.min(30,(ownUnits.filter(u=>u.status==='AVAILABLE').length/Math.max(1,ownUnits.length))*30))},[ownIncidents,ownUnits]);
 return <section className="operations-shell">
  {tab==='AGENCY'&&<div className="ops-page"><header className="ops-hero"><small>AGENCY MANAGEMENT</small><h2>Leitstellenbetrieb</h2><p>Wachen, Fuhrpark, Technik und Verträge bestimmen deine langfristige Einsatzfähigkeit.</p></header><div className="ops-grid four">{services.map(service=><article className="ops-card" key={service}><small>{service}</small><h3>{state.facilities.filter(f=>f.ownerId===playerId&&f.type===`${service}_STATION`).length} Wachen</h3><b>{ownUnits.filter(u=>u.service===service).length} Einheiten</b><span>Verfügbarkeit {Math.round(ownUnits.filter(u=>u.service===service&&u.status==='AVAILABLE').length/Math.max(1,ownUnits.filter(u=>u.service===service).length)*100)}%</span></article>)}</div><div className="ops-grid three">{ownFacilities.map(f=><article className="ops-card" key={f.id}><small>{f.type}</small><h3>{f.name}</h3><b>LEVEL {f.level??1}</b><p>{(f.upgrades??[]).length} Ausbauten</p><div className="ops-actions">{Object.entries(upgradeCosts).map(([k,c])=><button key={k} onClick={()=>send({type:'UPGRADE_FACILITY',facilityId:f.id,upgrade:k})}>{k} · {money(c)}</button>)}</div></article>)}</div><div className="ops-card wide"><small>VERTRÄGE</small><div className="contract-list">{CONTRACTS.map(c=><div key={c.id}><b>{c.name}</b><span>{money(c.payment)} / 30 Tage</span><button disabled={profile.reputation<c.minimumReputation} onClick={()=>{send({type:'ACTIVATE_CONTRACT',contractId:c.id});notice(`Vertrag ${c.name} angefragt.`)}}>{profile.reputation>=c.minimumReputation?'AKTIVIEREN':`AB REP ${c.minimumReputation}`}</button></div>)}</div></div></div>}
  {tab==='PERSONNEL'&&<div className="ops-page"><header className="ops-hero"><small>HUMAN RESOURCES</small><h2>Dispatcher & Schichten</h2><p>Stress, Müdigkeit, Ausbildung und Schichtplanung wirken direkt auf die Einsatzbearbeitung.</p></header><div className="ops-grid three">{ownStaff.map(p=><article className="ops-card" key={p.id}><small>{p.shift}</small><h3>{p.name}</h3><div className="stat-line"><span>ERFAHRUNG</span><b>{p.experience}</b></div><div className="meter"><i style={{width:`${p.performance}%`}}/></div><div className="stat-line"><span>PERFORMANCE</span><b>{p.performance}%</b></div><div className="stat-line"><span>STRESS</span><b>{Math.round(p.stress)}%</b></div><div className="stat-line"><span>ERSCHÖPFUNG</span><b>{Math.round(p.fatigue??0)}%</b></div><div className="stat-line"><span>FEHLERQUOTE</span><b>{p.errorRate.toFixed(1)}%</b></div><div className="ops-actions"><button onClick={()=>send({type:'TRAIN_PERSONNEL',personnelId:p.id})}>AUSBILDEN</button>{(['MORNING','AFTERNOON','NIGHT'] as const).map(s=><button key={s} onClick={()=>send({type:'SET_SHIFT',personnelId:p.id,shift:s})}>{s}</button>)}</div></article>)}</div><div className="ops-card wide"><button className="hero-button" onClick={()=>send({type:'HIRE_PERSONNEL'})}>DISPATCHER EINSTELLEN · $6.800/Monat</button></div></div>}
  {tab==='HOSPITALS'&&<div className="ops-page"><header className="ops-hero"><small>MEDICAL NETWORK</small><h2>Krankenhauskoordination</h2><p>Kapazität, Trauma, Verbrennungen, Pädiatrie und Helipad beeinflussen die Wahl des Zielkrankenhauses.</p></header><div className="ops-grid three">{state.hospitals.map(h=><article className="ops-card" key={h.id}><small>{h.id}</small><h3>{h.name}</h3><div className="hospital-cap"><i style={{width:`${Math.min(100,h.occupied/h.capacity*100)}%`}}/></div><b>{h.occupied} / {h.capacity}</b><div className="tag-row"><span>{h.trauma?'TRAUMA':''}</span><span>{h.burn?'BURN':''}</span><span>{h.pediatric?'PEDIATRIC':''}</span><span>{h.helipad?'HELIPAD':''}</span></div></article>)}</div><div className="ops-card wide"><small>AKTUELLE PATIENTEN</small>{(state.patients??[]).length===0?<p>Keine Patienten im zentralen Transportpool.</p>:<div className="patient-list">{(state.patients??[]).slice(0,30).map(p=><div key={p.id}><b>{p.id}</b><span>{p.severity}</span><span>{p.condition}</span><span>{p.survival.toFixed(0)}% Überleben</span><button disabled={!p.incidentId} onClick={()=>send({type:'TRANSPORT_PATIENTS',incidentId:p.incidentId})}>TRANSPORT</button></div>)}</div>}</div></div>}
  {tab==='WORLD'&&<div className="ops-page"><header className="ops-hero"><small>REDWOOD STATE OPERATIONS</small><h2>Weltlage</h2><p>Die Region reagiert auf Tageszeit, Wochentage, Wetter, Verkehr und Infrastruktur.</p></header><div className="ops-grid four"><article className="ops-card"><small>UHR</small><h3>{String(state.world.hour).padStart(2,'0')}:{String(state.world.minute).padStart(2,'0')}</h3><b>TAG {state.world.day}</b><span>{state.world.isWeekend?'WOCHENENDE':'WERKTAG'}</span></article><article className="ops-card"><small>WETTER</small><h3>{weatherLabel(state.world.weather)}</h3><span>{state.world.eventRate.toFixed(2)}× Ereignisrate</span></article><article className="ops-card"><small>VERKEHR</small><h3>{Math.round(state.world.traffic)}%</h3><span>Netzlast & ETA-Effekt</span></article><article className="ops-card"><small>BEVÖLKERUNG</small><h3>{state.world.population.toLocaleString('de-DE')}</h3><span>Emergency Level {state.world.emergencyLevel??1}</span></article></div><div className="ops-grid three">{CITIES.map(c=><article className="ops-card" key={c.id}><small>REGION</small><h3>{c.name}</h3><span>Population {c.population.toLocaleString('en-US')}</span><span>Crime {c.crime}% · Fire Risk {c.fireRisk}%</span><span>Traffic {c.traffic}% · Medical {c.medicalRisk}%</span></article>)}</div><div className="ops-card wide"><small>PRESSE & ÖFFENTLICHKEIT</small>{(state.news??[]).length===0?<p>Noch keine Presseereignisse.</p>:(state.news??[]).slice(0,8).map(n=><div className={`news-row ${n.severity.toLowerCase()}`} key={n.id}><b>{n.headline}</b><span>{n.body}</span></div>)}</div></div>}
  {tab==='REPORTS'&&<div className="ops-page"><header className="ops-hero"><small>PERFORMANCE CENTER</small><h2>Betriebsberichte</h2><p>Bewerte Antwortzeit, Dispositionsqualität, Auslastung und Finanzentwicklung.</p></header><div className="ops-grid four"><article className="ops-card"><small>LEISTUNG</small><h3>{performance}%</h3><span>Dispatch Efficiency</span></article><article className="ops-card"><small>ABSCHLÜSSE</small><h3>{state.statistics.completed}</h3><span>Missionen abgeschlossen</span></article><article className="ops-card"><small>PATIENTEN</small><h3>{state.statistics.patientsSaved}</h3><span>Patienten gerettet/versorgt</span></article><article className="ops-card"><small>GELD</small><h3>{money(profile.money)}</h3><span>aktuelles Budget</span></article></div><div className="ops-grid three"><article className="ops-card"><small>FINANZEN</small><div className="stat-line"><span>Einnahmen</span><b>{money(state.finance.revenueToday)}</b></div><div className="stat-line"><span>Ausgaben</span><b>{money(state.finance.costsToday)}</b></div><div className="stat-line"><span>Wartung</span><b>{money(state.finance.maintenance)}</b></div><div className="stat-line"><span>Personal</span><b>{money(state.finance.payroll)}</b></div></article><article className="ops-card"><small>FLOTTENLAST</small>{services.map(s=><div className="stat-line" key={s}><span>{s}</span><b>{ownUnits.filter(u=>u.service===s&&u.status!=='AVAILABLE').length}/{ownUnits.filter(u=>u.service===s).length}</b></div>)}</article><article className="ops-card"><small>ROUTING</small><div className="stat-line"><span>Gefahrene Meilen</span><b>{Math.round(state.statistics.milesDriven??0)}</b></div><div className="stat-line"><span>Ø Response</span><b>{state.statistics.averageResponse.toFixed(1)} min</b></div><div className="stat-line"><span>False Alarms</span><b>{state.statistics.falseAlarms}</b></div></article></div></div>}
  {tab==='RANKS'&&<div className="ops-page"><header className="ops-hero"><small>CAREER</small><h2>{progressionTitle(profile.level??1)}</h2><p>Level {profile.level} · {profile.xp%xpForNextLevel(profile.level)} / {xpForNextLevel(profile.level)} XP</p></header><div className="ops-grid three">{levelInfo(profile.level).unlocks.map(u=><article className="ops-card" key={u}><small>UNLOCK</small><h3>{u}</h3><span>Mit deinem aktuellen Fortschritt verfügbar.</span></article>)}</div></div>}
  {tab==='SETTINGS'&&<div className="ops-page"><header className="ops-hero"><small>SYSTEM</small><h2>Einstellungen</h2><p>Sprache, Audio, Darstellung und Simulationskomfort.</p></header><div className="ops-grid two"><article className="ops-card"><small>PROFIL</small><label>Dispatcher Name<input value={name} onChange={e=>setName(e.target.value)} onBlur={()=>{localStorage.setItem('ad-profile-name',name);notice('Profilname gespeichert.')}}/></label><label>Schwierigkeit<select value={difficulty} onChange={e=>{setDifficulty(e.target.value);localStorage.setItem('ad-difficulty',e.target.value)}}><option>RELAXED</option><option>NORMAL</option><option>HARD</option><option>REALISTIC</option></select></label><p>Schwierigkeit {difficulty} wirkt auf Ereignisrate, Verkehr und Eskalation.</p></article><article className="ops-card"><small>AUDIO MIXER</small>{(Object.keys(channelLabels) as AudioChannel[]).map(ch=><label className="slider-row" key={ch}><span>{channelLabels[ch]}</span><input type="range" min="0" max="100" value={Math.round(audio[ch]*100)} onChange={e=>{const v=Number(e.target.value)/100;setAudioChannel(ch,v);setAudio(getAudioSettings())}}/><b>{Math.round(audio[ch]*100)}%</b></label>)}</article></div></div>}
  {tab==='ADMIN'&&<div className="ops-page"><header className="ops-hero"><small>AUTHORIZED ADMINISTRATION</small><h2>Server & Debug</h2><p>Administrationsaktionen werden serverseitig berechtigt und validiert.</p></header><div className="ops-grid two"><article className="ops-card"><small>SERVER</small><div className="stat-line"><span>Verbindung</span><b>{connected?'ONLINE':'OFFLINE'}</b></div><div className="stat-line"><span>Spieler</span><b>{players.length}</b></div><div className="stat-line"><span>Einheiten</span><b>{state.units.length}</b></div><div className="stat-line"><span>Einsätze</span><b>{state.incidents.length}</b></div><div className="ops-actions"><button disabled={profile.role!=='ADMINISTRATOR'} onClick={()=>send({type:'ADMIN_SPAWN_INCIDENT'})}>EINSATZ ERZEUGEN</button><button disabled={profile.role!=='ADMINISTRATOR'} onClick={()=>send({type:'ADMIN_WEATHER',weather:'THUNDERSTORM'})}>GEWITTER</button><button disabled={profile.role!=='ADMINISTRATOR'} onClick={()=>send({type:'ADMIN_MONEY',delta:100000})}>+$100.000</button></div></article><article className="ops-card"><small>SPIELERROLLEN</small>{players.map(p=><div className="player-row" key={p.id}><b>{p.name}</b><span>{p.role}</span>{(profile.role==='ADMINISTRATOR'||p.id===playerId)&&<select value={p.role} onChange={e=>send({type:'SET_ROLE',playerId:p.id,role:e.target.value})}>{roles.map(r=><option key={r}>{r}</option>)}</select>}</div>)}</article></div></div>}
 </section>
}
