import { useMemo, useState } from 'react';
import type { GameState, Service } from '../game/state';
import { getAudioSettings, setAudioChannel, type AudioChannel } from '../game/audio-bus';
import { CONTRACTS } from '../game/contracts';
import { CITIES } from '../game/catalog';
import { levelInfo, progressionTitle, xpForNextLevel } from '../game/progression';
import { weatherLabel } from '../game/state';

export type OpsTab='AGENCY'|'PERSONNEL'|'HOSPITALS'|'WORLD'|'REPORTS'|'SETTINGS'|'ADMIN'|'RANKS';
type Props={tab:OpsTab;state:GameState;profile:any;playerId:string;connected:boolean;send:(message:unknown)=>boolean;notice:(message:string)=>void};
const services:Service[]=['POLICE','FIRE','EMS'];const roles=['CALL_TAKER','POLICE_DISPATCHER','FIRE_DISPATCHER','EMS_DISPATCHER','SUPERVISOR','MANAGER','ADMINISTRATOR'] as const;const costs:Record<string,number>={FLEET:35000,STAFF:25000,CELLS:30000,APPARATUS:45000,MEDICAL:40000,STORAGE:20000};const channels:Record<AudioChannel,string>={MASTER:'Master',UI:'Interface',RADIO:'Funk',CALLS:'Notrufe',VEHICLES:'Fahrzeuge',ALARMS:'Alarme',MUSIC:'Musik'};const money=(v:number)=>`$${Math.max(0,Math.round(v)).toLocaleString('en-US')}`;

export function OperationsDashboard({tab,state,profile,playerId,connected,send,notice}:Props){
 const owner=(state as any).__ownerToken??playerId;const ownUnits=state.units.filter(u=>u.ownerId===owner);const ownFacilities=state.facilities.filter(f=>f.ownerId===owner);const ownStaff=state.personnel.filter(p=>p.ownerId===owner);const ownIncidents=state.incidents.filter(i=>i.ownerId===owner);const [name,setName]=useState(profile.playerName??'Dispatcher');const [difficulty,setDifficulty]=useState(profile.difficulty??(state as any).__difficulty??'NORMAL');const [audio,setAudio]=useState(getAudioSettings());const players=((state as any).__lobby?.players??[]) as Array<{id:string;name:string;role:string}>;const performance=useMemo(()=>{const total=Math.max(1,ownIncidents.length);return Math.round(ownIncidents.filter(i=>i.status==='COMPLETE').length/total*70+(ownUnits.length?ownUnits.filter(u=>u.status==='AVAILABLE').length/ownUnits.length*30:0))},[ownIncidents,ownUnits]);
 const Header=({kicker,title,sub}:{kicker:string;title:string;sub:string})=><header className="ops-hero"><small>{kicker}</small><h2>{title}</h2><p>{sub}</p></header>;const Card=({children}:{children:React.ReactNode})=><article className="ops-card">{children}</article>;const Line=({a,b}:{a:string;b:React.ReactNode})=><div className="stat-line"><span>{a}</span><b>{b}</b></div>;
 if(tab==='AGENCY')return <div className="ops-page"><Header kicker="LEITSTELLENBETRIEB" title="Wachen & Fuhrpark" sub="Baue, erweitere und unterhalte deine Einsatzorganisation."/><div className="ops-grid four">{services.map(s=><Card key={s}><small>{s}</small><h3>{ownFacilities.filter(f=>f.type===`${s}_STATION`).length} Wachen</h3><Line a="Einheiten" b={ownUnits.filter(u=>u.service===s).length}/><Line a="Verfügbar" b={ownUnits.filter(u=>u.service===s&&u.status==='AVAILABLE').length}/></Card>)}</div><div className="ops-grid three">{ownFacilities.map(f=><Card key={f.id}><small>{f.type}</small><h3>{f.name}</h3><Line a="Stufe" b={f.level??1}/><Line a="Ausbauten" b={(f.upgrades??[]).length}/><div className="ops-actions">{Object.entries(costs).map(([k,c])=><button key={k} onClick={()=>send({type:'UPGRADE_FACILITY',facilityId:f.id,upgrade:k})}>{k} · {money(c)}</button>)}</div></Card>)}</div><Card><small>VERTRÄGE</small><div className="contract-list">{CONTRACTS.map(c=><div key={c.id}><b>{c.name}</b><span>{money(c.payment)} / 30 Tage</span><button disabled={(profile.reputation??72)<c.minimumReputation} onClick={()=>send({type:'ACTIVATE_CONTRACT',contractId:c.id})}>{(profile.reputation??72)>=c.minimumReputation?'AKTIVIEREN':`AB REP ${c.minimumReputation}`}</button></div>)}</div></Card></div>;
 if(tab==='PERSONNEL')return <div className="ops-page"><Header kicker="PERSONAL" title="Dispatcher & Schichten" sub="Ausbildung, Stress, Müdigkeit und Schichtplanung verändern die Einsatzqualität."/><div className="ops-grid three">{ownStaff.map(p=><Card key={p.id}><small>{p.shift}</small><h3>{p.name}</h3><Line a="Erfahrung" b={p.experience}/><Line a="Performance" b={`${p.performance}%`}/><Line a="Stress" b={`${Math.round(p.stress)}%`}/><Line a="Müdigkeit" b={`${Math.round(p.fatigue??0)}%`}/><Line a="Fehlerquote" b={`${p.errorRate.toFixed(1)}%`}/><div className="ops-actions"><button onClick={()=>send({type:'TRAIN_PERSONNEL',personnelId:p.id})}>AUSBILDEN · $2.500</button>{(['MORNING','AFTERNOON','NIGHT'] as const).map(x=><button key={x} onClick={()=>send({type:'SET_SHIFT',personnelId:p.id,shift:x})}>{x}</button>)}</div></Card>)}</div><Card><button className="hero-button" onClick={()=>send({type:'HIRE_PERSONNEL'})}>DISPATCHER EINSTELLEN</button></Card></div>;
 if(tab==='HOSPITALS')return <div className="ops-page"><Header kicker="EMS NETWORK" title="Krankenhäuser & Patienten" sub="Kapazitäten und Spezialversorgung bestimmen die Transportwege."/><div className="ops-grid three">{state.hospitals.map(h=><Card key={h.id}><small>{h.id}</small><h3>{h.name}</h3><Line a="Belegung" b={`${h.occupied}/${h.capacity}`}/><div className="hospital-cap"><i style={{width:`${Math.min(100,h.occupied/h.capacity*100)}%`}}/></div><div className="tag-row">{h.trauma&&<span>TRAUMA</span>}{h.burn&&<span>BURN</span>}{h.pediatric&&<span>PEDIATRIC</span>}{h.helipad&&<span>HELIPAD</span>}</div></Card>)}</div><Card><small>PATIENTENPOOL</small>{(state.patients??[]).slice(0,40).map(p=><div className="patient-list" key={p.id}><div><b>{p.id}</b><span>{p.severity}</span><span>{p.condition}</span><span>{p.survival.toFixed(0)}%</span><select defaultValue="AUTO" onChange={e=>send({type:'TRANSPORT_PATIENTS',incidentId:p.incidentId,hospitalId:e.target.value==='AUTO'?undefined:e.target.value})}><option value="AUTO">AUTO KRANKENHAUS</option>{state.hospitals.map(h=><option value={h.id} key={h.id}>{h.name}</option>)}</select></div></div>)}</Card></div>;
 if(tab==='WORLD')return <div className="ops-page"><Header kicker="REDWOOD STATE" title="Weltlage" sub="Tageszeit, Wetter, Verkehr, Wochenenden und regionale Risiken beeinflussen die Einsatzrate."/><div className="ops-grid four"><Card><small>UHR</small><h3>{String(state.world.hour).padStart(2,'0')}:{String(state.world.minute).padStart(2,'0')}</h3><span>Tag {state.world.day} · {state.world.dayPart} · {state.world.isWeekend?'Wochenende':'Werktag'}</span></Card><Card><small>WETTER</small><h3>{weatherLabel(state.world.weather)}</h3><span>{state.world.eventRate.toFixed(2)}× Ereignisrate</span></Card><Card><small>VERKEHR</small><h3>{Math.round(state.world.traffic)}%</h3><span>Beeinflusst ETA und Unfälle</span></Card><Card><small>BEVÖLKERUNG</small><h3>{state.world.population.toLocaleString('de-DE')}</h3><span>Emergency Level {state.world.emergencyLevel??1}</span></Card></div><div className="ops-grid three">{CITIES.map(c=><Card key={c.id}><small>REGION</small><h3>{c.name}</h3><span>Population {c.population.toLocaleString('en-US')}</span><span>Crime {c.crime}% · Fire {c.fireRisk}%</span><span>Traffic {c.traffic}% · Medical {c.medicalRisk}%</span></Card>)}</div><Card><small>PRESSE</small>{(state.news??[]).slice(0,12).map(n=><div className={`news-row ${n.severity.toLowerCase()}`} key={n.id}><b>{n.headline}</b><span>{n.body}</span></div>)}</Card></div>;
 if(tab==='REPORTS')return <div className="ops-page"><Header kicker="BETRIEBSBERICHT" title="Dispatch Performance" sub="Messwerte für Einsatzqualität, Flotte und Finanzen."/><div className="ops-grid four"><Card><small>EFFIZIENZ</small><h3>{performance}%</h3></Card><Card><small>ABSCHLÜSSE</small><h3>{ownIncidents.filter(i=>i.status==='COMPLETE').length}</h3></Card><Card><small>PATIENTEN</small><h3>{state.statistics.patientsSaved}</h3></Card><Card><small>REPUTATION</small><h3>{Math.round(profile.reputation??72)}%</h3></Card></div><div className="ops-grid three"><Card><small>FINANZEN</small><Line a="Einnahmen" b={money(state.finance.revenueToday)}/><Line a="Ausgaben" b={money(state.finance.costsToday)}/><Line a="Wartung" b={money(state.finance.maintenance)}/><Line a="Personal" b={money(state.finance.payroll)}/><Line a="Reserve" b={money(state.finance.emergencyReserve??0)}/></Card><Card><small>FLOTTENLAST</small>{services.map(s=><Line key={s} a={s} b={`${ownUnits.filter(u=>u.service===s&&u.status!=='AVAILABLE').length}/${ownUnits.filter(u=>u.service===s).length}`}/>)}</Card><Card><small>ROUTING</small><Line a="Meilen" b={Math.round(state.statistics.milesDriven??0)}/><Line a="Ø Response" b={`${state.statistics.averageResponse.toFixed(1)} min`}/><Line a="False Alarms" b={state.statistics.falseAlarms}/></Card></div></div>;
 if(tab==='RANKS')return <div className="ops-page"><Header kicker="KARRIERE" title={progressionTitle(profile.level??1)} sub={`Level ${profile.level} · ${profile.xp%xpForNextLevel(profile.level)} / ${xpForNextLevel(profile.level)} XP`}/><div className="ops-grid three">{levelInfo(profile.level??1).unlocks.map(x=><Card key={x}><small>FREISCHALTUNG</small><h3>{x}</h3></Card>)}</div></div>;
 if(tab==='SETTINGS')return <div className="ops-page"><Header kicker="SYSTEM" title="Einstellungen" sub="Profil, Simulation, Audio und Spielstände."/><div className="ops-grid two"><Card><small>PROFIL</small><label>Name<input value={name} onChange={e=>setName(e.target.value)} onBlur={()=>{const p={...profile,playerName:name};localStorage.setItem('ad-profile-v6',JSON.stringify(p));notice('Profil gespeichert.')}}/></label><label>Schwierigkeit<select value={difficulty} onChange={e=>{const v=e.target.value;setDifficulty(v);send({type:'SET_DIFFICULTY',difficulty:v})}}><option>RELAXED</option><option>NORMAL</option><option>HARD</option><option>REALISTIC</option></select></label><div className="ops-actions"><button onClick={()=>send({type:'SAVE_GAME',name:'manual'})}>SPEICHERN</button><button onClick={()=>send({type:'LOAD_GAME',name:'manual'})}>LADEN</button></div></Card><Card><small>AUDIO</small>{(Object.keys(channels) as AudioChannel[]).map(ch=><label className="slider-row" key={ch}><span>{channels[ch]}</span><input type="range" min="0" max="100" value={Math.round(audio[ch]*100)} onChange={e=>{setAudioChannel(ch,Number(e.target.value)/100);setAudio(getAudioSettings())}}/><b>{Math.round(audio[ch]*100)}%</b></label>)}</Card></div></div>;
 return <div className="ops-page"><Header kicker="ADMINISTRATION" title="Server & Debug" sub="Autorisierte Serveraktionen und Multiplayer-Verwaltung."/><div className="ops-grid two"><Card><Line a="Verbindung" b={connected?'ONLINE':'OFFLINE'}/><Line a="Spieler" b={players.length}/><Line a="Einheiten" b={state.units.length}/><Line a="Aktive Einsätze" b={state.incidents.filter(i=>!['COMPLETE','CANCELLED'].includes(i.status)).length}/><Line a="Server Tick" b={(state as any).__debug?.serverTick??0}/><div className="ops-actions"><button disabled={profile.role!=='ADMINISTRATOR'} onClick={()=>send({type:'ADMIN_SPAWN_INCIDENT'})}>EINSATZ ERZEUGEN</button><button disabled={profile.role!=='ADMINISTRATOR'} onClick={()=>send({type:'ADMIN_WEATHER',weather:'THUNDERSTORM'})}>GEWITTER</button><button disabled={profile.role!=='ADMINISTRATOR'} onClick={()=>send({type:'ADMIN_MONEY',delta:100000})}>+$100.000</button></div></Card><Card><small>ROLLEN</small>{players.map(p=><div className="player-row" key={p.id}><b>{p.name}</b><select value={p.role} onChange={e=>send({type:'SET_ROLE',playerId:p.id,role:e.target.value})} disabled={profile.role!=='ADMINISTRATOR'}>{roles.map(r=><option key={r}>{r}</option>)}</select><button disabled={profile.role!=='ADMINISTRATOR'||p.id===playerId} onClick={()=>send({type:'KICK_PLAYER',playerId:p.id})}>KICK</button></div>)}</Card></div></div>;
}
