import { useEffect, useMemo, useRef, useState } from 'react';
import { Map, NavigationControl, ScaleControl, setWorkerUrl } from 'maplibre-gl';
import workerUrl from 'maplibre-gl/dist/maplibre-gl-worker.mjs?worker&url';
import 'maplibre-gl/dist/maplibre-gl.css';
import type { GameState, Service, MapPoint } from '../game/state';
import { playDispatchAlert, playRadioPing, playSiren, toggleAmbient } from '../game/audio';
import './real-map.css';

type Point=MapPoint;
const serviceColor=(s:Service)=>s==='POLICE'?'#1668b2':s==='FIRE'?'#c62832':'#087f5b';
const facilityStyle:Record<string,{icon:string;color:string}>={POLICE_STATION:{icon:'P',color:'#1668b2'},FIRE_STATION:{icon:'F',color:'#c62832'},EMS_STATION:{icon:'R',color:'#087f5b'},HOSPITAL:{icon:'H',color:'#087f5b'},SCHOOL:{icon:'S',color:'#8a6400'},FUEL:{icon:'$',color:'#8a6400'},SHOPPING:{icon:'M',color:'#7b3f98'},INDUSTRIAL:{icon:'I',color:'#8c4a38'},AIRPORT:{icon:'A',color:'#456b91'},RAIL:{icon:'R',color:'#455a64'},PARK:{icon:'P',color:'#347a4b'},BRIDGE:{icon:'B',color:'#735421'}};
const bounds={west:-122.285,east:-122.185,south:37.455,north:37.535};
const toLngLat=(p:Point):[number,number]=>[bounds.west+p.x/100*(bounds.east-bounds.west),bounds.north-p.y/100*(bounds.north-bounds.south)];
const fromLngLat=(lng:number,lat:number):Point=>({x:((lng-bounds.west)/(bounds.east-bounds.west))*100,y:((bounds.north-lat)/(bounds.north-bounds.south))*100});
function Vehicle({unit}:{unit:GameState['units'][number]}){
 const moving=unit.status==='EN_ROUTE'||unit.status==='RETURNING';
 const heading=unit.heading??0;
 const raw=unit.type||'';
 const supervisor=/supervisor|command/i.test(`${raw} ${unit.callsign} ${unit.capabilities.join(' ')}`);
 const ladder=/ladder|truck/i.test(raw)||/ladder/i.test(unit.callsign);
 const rescue=/rescue/i.test(raw)||/rescue/i.test(unit.callsign);
 const ambulance=/ambulance|medic|ems/i.test(`${raw} ${unit.callsign}`);
 const police=/police|patrol|supervisor|command/i.test(`${raw} ${unit.callsign}`);
 const short=supervisor?'SUP':ladder?'L':rescue?'R':ambulance?'A':police?'P':unit.callsign.slice(0,3);
 return <div className={`rv ${unit.service.toLowerCase()} ${supervisor?'supervisor':''} ${ladder?'ladder':''} ${rescue?'rescue':''} ${ambulance?'ambulance':''} ${moving?'moving':''}`} style={{transform:`translate(-50%,-50%) rotate(${heading}deg)`}}><span className="rv-glow"/><span className="rv-body"><i className="rv-cab"/><i className="rv-window"/>{ladder&&<i className="rv-ladder"/>}{rescue&&<i className="rv-rescue"/>}{supervisor&&<i className="rv-command"/>}{ambulance&&<i className="rv-medical"/>}{police&&<i className="rv-police-mark"/>}<i className="rv-wheel w1"/><i className="rv-wheel w2"/><i className="rv-wheel w3"/><i className="rv-wheel w4"/><i className="rv-light l1"/><i className="rv-light l2"/></span><b>{short}</b></div>
}
export function RealMapView({state,zoom,onZoomChange,onIncidentSelect,buildMode,onMapBuild}:{state:GameState;zoom:number;onZoomChange:(z:number)=>void;onIncidentSelect:(id:string)=>void;buildMode?:Service|null;onMapBuild?:(p:Point)=>void}){
 const ref=useRef<HTMLDivElement|null>(null);const mapRef=useRef<Map|null>(null);const [ready,setReady]=useState(false);const [failed,setFailed]=useState(false);const [ambient,setAmbient]=useState(false);const [units,setUnits]=useState(true);const [incidents,setIncidents]=useState(true);const [poi,setPoi]=useState(true);const [traffic,setTraffic]=useState(false);const [,tick]=useState(0);const facilities=state.facilities??[];const active=state.incidents.filter(i=>!['COMPLETE','CANCELLED'].includes(i.status));
 useEffect(()=>{if(!ref.current||mapRef.current)return;setWorkerUrl(workerUrl);const map=new Map({container:ref.current,style:'https://tiles.openfreemap.org/styles/bright',center:[-122.235,37.49],zoom:13,minZoom:11,maxZoom:18,dragRotate:false,pitchWithRotate:false,keyboard:true,attributionControl:{compact:true},renderWorldCopies:false,maxBounds:[[-122.31,37.43],[-122.16,37.56]]});map.addControl(new NavigationControl({showCompass:false,visualizePitch:false}),'bottom-right');map.addControl(new ScaleControl({maxWidth:140,unit:'imperial'}),'bottom-left');map.on('load',()=>{setReady(true);map.resize()});map.on('move',()=>tick(v=>v+1));map.on('error',e=>{const m=e?.error?.message?.toLowerCase()??'';if(m.includes('style')||m.includes('worker')||m.includes('source'))setFailed(true)});mapRef.current=map;return()=>{map.remove();mapRef.current=null}},[]);
 useEffect(()=>{const map=mapRef.current;if(!map||!ready)return;const handler=(event:any)=>{if(!buildMode||!onMapBuild)return;const p=fromLngLat(event.lngLat.lng,event.lngLat.lat);if(p.x<0||p.x>100||p.y<0||p.y>100)return;onMapBuild(p)};if(buildMode){map.getCanvas().style.cursor='crosshair';map.on('click',handler)}else{map.getCanvas().style.cursor='';}return()=>{map.off('click',handler);if(!buildMode)map.getCanvas().style.cursor=''}},[buildMode,onMapBuild,ready]);
 useEffect(()=>{if(mapRef.current&&ready)mapRef.current.setZoom(12.15+Math.log2(Math.max(.7,zoom)))},[zoom,ready]);
 const routeFeatures=useMemo(()=>state.units.filter(u=>u.route&&u.route.length>1&&(u.status==='EN_ROUTE'||u.status==='RETURNING')).map(u=>({color:serviceColor(u.service),coordinates:u.route!.map(toLngLat)})),[state.units]);
 useEffect(()=>{const map=mapRef.current;if(!map||!ready)return;const data={type:'FeatureCollection',features:routeFeatures.map(r=>({type:'Feature',properties:{color:r.color},geometry:{type:'LineString',coordinates:r.coordinates}}))};const src=map.getSource('dispatch-routes') as any;if(src){src.setData(data);return}map.addSource('dispatch-routes',{type:'geojson',data} as any);map.addLayer({id:'dispatch-routes-glow',type:'line',source:'dispatch-routes',paint:{'line-color':['get','color'],'line-width':6,'line-opacity':.09,'line-blur':3}} as any);map.addLayer({id:'dispatch-routes',type:'line',source:'dispatch-routes',paint:{'line-color':['get','color'],'line-width':2,'line-opacity':.72,'line-dasharray':[1.5,2]}} as any)},[routeFeatures,ready]);
 const project=(p:Point)=>mapRef.current?.project(toLngLat(p));
 const select=(id:string)=>{playRadioPing();playDispatchAlert();onIncidentSelect(id)};
 return <div className={`map-shell real-cad-map ${buildMode?'building':''}`}><div className="real-toolbar">{buildMode&&<div className="build-live-indicator">BAUEN · LINKSKLICK</div>}<button onClick={()=>onZoomChange(Math.min(3,zoom+.25))}>＋</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>onZoomChange(Math.max(.65,zoom-.25))}>−</button><button onClick={()=>onZoomChange(1)}>⌂</button><i className="toolbar-sep"/><button className={units?'on':''} onClick={()=>setUnits(v=>!v)}>UNITS</button><button className={incidents?'on':''} onClick={()=>setIncidents(v=>!v)}>911</button><button className={poi?'on':''} onClick={()=>setPoi(v=>!v)}>POI</button><button className={traffic?'on':''} onClick={()=>setTraffic(v=>!v)}>TRAFFIC</button><i className="toolbar-sep"/><button className={ambient?'on':''} onClick={()=>setAmbient(toggleAmbient())}>♫</button><button onClick={playRadioPing}>RADIO</button><button onClick={playSiren}>SIREN</button></div><div className="real-status"><div><b>REDWOOD CITY / SAN CARLOS</b><small>PUBLIC SAFETY CAD</small></div><span>{state.world.weather} · TRAFFIC {state.world.traffic}% · {state.world.nightFactor?'NIGHT':'DAY'}</span></div><div className="map-corner north">N<br/><span>↑</span></div><div ref={ref} className={`real-map-canvas ${failed?'failed':''}`}/>{buildMode&&<div className="build-hint"><b>BAUPLATZ WÄHLEN · LINKSKLICK</b><span>Klicke direkt auf die Karte. Der Punkt ist frei wählbar – die Wache wird genau dort gebaut und deine Fahrzeuge starten von dort.</span></div>}<div className="real-overlay">{traffic&&<div className="traffic-panel"><b>NETWORK</b><span>{state.world.traffic}%</span><i style={{width:`${state.world.traffic}%`}}/></div>}{poi&&ready&&facilities.map(f=>{const p=project(f.position);if(!p)return null;const s=facilityStyle[f.type]??{icon:'?',color:'#455a64'};return <button key={f.id} className="poi-badge" style={{left:p.x,top:p.y,borderColor:s.color}} onClick={playRadioPing} title={f.name}><span style={{color:s.color}}>{s.icon}</span></button>})}{incidents&&ready&&active.map(i=>{const p=project(i.location);if(!p)return null;return <button key={i.id} className={`incident-badge ${i.priority===1?'critical':''}`} style={{left:p.x,top:p.y}} onClick={()=>select(i.id)}><span/><b>{i.id}</b><small>P{i.priority}</small></button>})}{units&&ready&&state.units.map(u=>{const p=project(u.position);if(!p)return null;return <div key={u.id} className="rv-wrap" style={{left:p.x,top:p.y}}><Vehicle unit={u}/></div>})}</div><div className="real-legend"><span><i className="dot police"/> POLICE</span><span><i className="dot fire"/> FIRE</span><span><i className="dot ems"/> EMS</span><span><i className="dot incident"/> 911</span><span>Map data © OpenStreetMap contributors</span></div><div className="real-footer"><b>LIVE CAD</b> · {state.units.length} OWN UNITS · {active.length} ACTIVE · REAL OSM BASEMAP</div></div>}
