import { useEffect, useMemo, useRef, useState } from 'react';
import { Map, NavigationControl } from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
import type { GameState, Facility, Service } from '../game/state';
import { playDispatchAlert, playRadioPing, playSiren, toggleAmbient } from '../game/audio';
import './real-map.css';

type Point={x:number;y:number};
const serviceColor=(s:Service)=>s==='POLICE'?'#4da3ff':s==='FIRE'?'#ef535b':'#4fd39a';
const facilityStyle:Record<Facility['type'],{icon:string;color:string}>={POLICE_STATION:{icon:'P',color:'#4da3ff'},FIRE_STATION:{icon:'F',color:'#ef535b'},HOSPITAL:{icon:'H',color:'#4fd39a'},SCHOOL:{icon:'S',color:'#e3bd67'},FUEL:{icon:'$',color:'#e3bd67'},SHOPPING:{icon:'M',color:'#c98be8'},INDUSTRIAL:{icon:'I',color:'#d47e68'},AIRPORT:{icon:'A',color:'#7da9d8'},RAIL:{icon:'R',color:'#aeb9c0'},PARK:{icon:'P',color:'#65b779'},BRIDGE:{icon:'B',color:'#d2aa65'}};
const bounds={west:-122.285,east:-122.185,south:37.455,north:37.535};
const toLngLat=(p:Point):[number,number]=>[bounds.west+p.x/100*(bounds.east-bounds.west),bounds.north-p.y/100*(bounds.north-bounds.south)];

function Vehicle({unit}:{unit:GameState['units'][number]}){const moving=unit.status==='EN_ROUTE'||unit.status==='RETURNING';const heading=unit.heading??(moving&&unit.target?Math.atan2(unit.target.y-unit.position.y,unit.target.x-unit.position.x)*180/Math.PI:0);const model=unit.vehicleModel??'';const suv=/Tahoe|Interceptor|Charger/i.test(model);const ladder=/Ladder|Truck/i.test(unit.type);return <div className={`rv ${unit.service.toLowerCase()} ${moving?'moving':''}`} style={{transform:`translate(-50%,-50%) rotate(${heading}deg)`}}><span className="rv-glow"/><span className="rv-body"><i className="rv-window"/>{suv&&<i className="rv-roof"/>}{ladder&&<i className="rv-ladder"/>}<i className="rv-wheel w1"/><i className="rv-wheel w2"/><i className="rv-wheel w3"/><i className="rv-wheel w4"/><i className="rv-light l1"/><i className="rv-light l2"/></span><b>{unit.callsign.replace('AMBULANCE','A').replace('PATROL','P').replace('ENGINE','E').replace('TRUCK','T').replace('BATTALION','B')}</b></div>}

export function RealMapView({state,zoom,onZoomChange,onIncidentSelect}:{state:GameState;zoom:number;onZoomChange:(z:number)=>void;onIncidentSelect:(id:string)=>void}){
 const ref=useRef<HTMLDivElement|null>(null);const mapRef=useRef<Map|null>(null);const [ready,setReady]=useState(false);const [failed,setFailed]=useState(false);const [ambient,setAmbient]=useState(false);const [units,setUnits]=useState(true);const [incidents,setIncidents]=useState(true);const [poi,setPoi]=useState(true);const [traffic,setTraffic]=useState(true);const [,tick]=useState(0);
 const nodes=state.roads?.nodes??[];const edges=state.roads?.edges??[];const facilities=state.facilities??[];const active=state.incidents.filter(i=>!['COMPLETE','CANCELLED'].includes(i.status));
 useEffect(()=>{if(!ref.current||mapRef.current)return;const map=new Map({container:ref.current,style:'https://tiles.openfreemap.org/styles/liberty',center:[-122.235,37.49],zoom:12.7,minZoom:11,maxZoom:18,dragRotate:false,pitchWithRotate:false});map.addControl(new NavigationControl({showCompass:false}),'bottom-right');map.on('load',()=>{setReady(true);map.resize()});map.on('move',()=>tick(v=>v+1));map.on('error',()=>setFailed(true));mapRef.current=map;return()=>{map.remove();mapRef.current=null}},[]);
 useEffect(()=>{if(mapRef.current&&ready)mapRef.current.setZoom(12.15+Math.log2(Math.max(.7,zoom)))},[zoom,ready]);
 const routes=useMemo(()=>state.units.filter(u=>u.target&&(u.status==='EN_ROUTE'||u.status==='RETURNING')).map(u=>({a:toLngLat(u.position),b:toLngLat(u.target!),color:serviceColor(u.service)})),[state.units]);
 useEffect(()=>{const map=mapRef.current;if(!map||!ready)return;const data={type:'FeatureCollection',features:routes.map(r=>({type:'Feature',properties:{color:r.color},geometry:{type:'LineString',coordinates:[r.a,r.b]}}))};const src=map.getSource('dispatch-routes') as any;if(src){src.setData(data);return}map.addSource('dispatch-routes',{type:'geojson',data} as any);map.addLayer({id:'dispatch-routes',type:'line',source:'dispatch-routes',paint:{'line-color':['get','color'],'line-width':2.5,'line-opacity':.9,'line-dasharray':[1,1.5]}} as any)},[routes,ready]);
 const project=(p:Point)=>mapRef.current?.project(toLngLat(p));
 const select=(id:string)=>{playRadioPing();playDispatchAlert();onIncidentSelect(id)};
 return <div className="map-shell real-cad-map"><div className="real-toolbar"><button onClick={()=>onZoomChange(Math.min(3,zoom+.25))}>＋</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>onZoomChange(Math.max(.65,zoom-.25))}>−</button><button onClick={()=>onZoomChange(1)}>⌂</button><button className={units?'on':''} onClick={()=>setUnits(v=>!v)}>UNITS</button><button className={incidents?'on':''} onClick={()=>setIncidents(v=>!v)}>911</button><button className={poi?'on':''} onClick={()=>setPoi(v=>!v)}>POI</button><button className={traffic?'on':''} onClick={()=>setTraffic(v=>!v)}>TRAFFIC</button><button className={ambient?'on':''} onClick={()=>setAmbient(toggleAmbient())}>♫</button><button onClick={playRadioPing}>RADIO</button><button onClick={playSiren}>SIRENE</button></div><div className="real-status"><b>REDWOOD METRO COUNTY</b><span>REAL MAP · {state.world.weather} · TRAFFIC {state.world.traffic}% · {state.world.nightFactor?'NIGHT':'DAY'}</span></div><div ref={ref} className={`real-map-canvas ${failed?'failed':''}`}/>{failed&&<div className="map-fallback-message">REAL MAP KANN NICHT GELADEN WERDEN · SIMULATIONS-KARTE AKTIV</div>}<div className="real-overlay">{traffic&&ready&&edges.map(e=>{const a=nodes.find(n=>n.id===e.from)?.position,b=nodes.find(n=>n.id===e.to)?.position;if(!a||!b)return null;const p=project({x:(a.x+b.x)/2,y:(a.y+b.y)/2});if(!p)return null;return <span key={e.id} className={`traffic-badge ${e.traffic>70?'hot':''}`} style={{left:p.x,top:p.y}}>{e.traffic}%</span>})}{poi&&ready&&facilities.map(f=>{const p=project(f.position);if(!p)return null;const s=facilityStyle[f.type];return <button key={f.id} className="poi-badge" style={{left:p.x,top:p.y,borderColor:s.color}} onClick={playRadioPing} title={f.name}><span style={{color:s.color}}>{s.icon}</span><small>{f.name}</small></button>})}{incidents&&ready&&active.map(i=>{const p=project(i.location);if(!p)return null;const critical=i.priority===1;return <button key={i.id} className={`incident-badge ${critical?'critical':''}`} style={{left:p.x,top:p.y}} onClick={()=>select(i.id)}><span/><b>{i.id}</b><small>P{i.priority} · {i.type}</small></button>})}{units&&ready&&state.units.map(u=>{const p=project(u.position);if(!p)return null;return <div key={u.id} className="rv-wrap" style={{left:p.x,top:p.y}}><Vehicle unit={u}/></div>})}</div><div className="real-legend"><span>● POLICE</span><span>● FIRE</span><span>● EMS</span><span>● 911</span><span>© OpenStreetMap contributors · OpenFreeMap</span></div><div className="real-footer"><b>LIVE CAD</b> · {state.units.length} UNITS · {active.length} ACTIVE · REAL-WORLD ROAD GEOMETRY · FICTIONAL INCIDENTS & UNITS</div></div>;
}
