import { createServer } from 'node:http';
import { mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { WebSocketServer, type WebSocket } from 'ws';
import { cloneState, formatClock, type GameState, type Service, type MapPoint, type Facility } from '../src/game/state';

type Client={id:string;name:string;ready:boolean};
type AidRequest={id:string;fromPlayerId:string;fromName:string;toPlayerId:string;incidentId:string;incidentSummary:string;location:string;requestedServices:Service[];requestedUnits:number;note:string;createdAt:number;status:'PENDING'|'ACCEPTED'|'DECLINED'|'COMPLETED'};
const clients=new Map<WebSocket,Client>();const aidRequests=new Map<string,AidRequest>();const lobby={id:'REDWOOD-1',name:'Redwood Metro Multiplayer',hostId:'',maxPlayers:16,players:[] as Array<Client&{connected:boolean}>};
const savePath=resolve(process.env.SAVE_FILE??'data/game-state.json');let lastAutoCall=Date.now()-30000;
function valid(v:unknown):v is GameState{const s=v as Partial<GameState>|null;return !!s&&s.version===2&&Array.isArray(s.units)&&Array.isArray(s.incidents)&&!!s.center&&!!s.world}
function load(){try{const s=JSON.parse(readFileSync(savePath,'utf8'));if(valid(s))return s}catch{}return cloneState()}
let state=load();
// Never revive legacy unowned dispatch vehicles. Only units belonging to a player are playable.
state.units=state.units.filter(u=>!!u.ownerId);
state.facilities=(state.facilities??[]).filter((f:any)=>f.ownerId||f.type==='HOSPITAL'||f.type==='AIRPORT'||f.type==='RAIL'||f.type==='SCHOOL'||f.type==='SHOPPING'||f.type==='INDUSTRIAL'||f.type==='PARK'||f.type==='BRIDGE');
let sequence=Math.max(10,...state.incidents.map(i=>Number(i.id.replace(/\D/g,''))||0))+1;
function persist(){try{mkdirSync(dirname(savePath),{recursive:true});const tmp=savePath+'.tmp';writeFileSync(tmp,JSON.stringify(state),'utf8');renameSync(tmp,savePath)}catch(e){console.error(e)}}
function syncLobby(){lobby.players=[...clients.values()].map(p=>({...p,connected:true}))}
function snapshot(){syncLobby();return{type:'STATE_SNAPSHOT',payload:state,lobby,playerCount:clients.size}}
function broadcast(v:unknown){const raw=JSON.stringify(v);for(const s of clients.keys())if(s.readyState===s.OPEN)s.send(raw)}
function broadcastAid(){broadcast({type:'MUTUAL_AID_SNAPSHOT',payload:[...aidRequests.values()]})}
function replyError(s:WebSocket,m:string){s.send(JSON.stringify({type:'ERROR',message:m}))}
function owns(c:Client,i:any){return i?.ownerId===c.id}
function nearest(p:MapPoint){return(state.roads?.nodes??[]).reduce<any>((best,n)=>!best||Math.hypot(n.position.x-p.x,n.position.y-p.y)<Math.hypot(best.position.x-p.x,best.position.y-p.y)?n:best,null)}
function route(from:MapPoint,to:MapPoint){const roads=state.roads;if(!roads)return[from,to];const a=nearest(from),b=nearest(to);if(!a||!b)return[from,to];const d=new Map<string,number>(roads.nodes.map(n=>[n.id,Infinity])),prev=new Map<string,string>(),open=new Set<string>([a.id]);d.set(a.id,0);while(open.size){const cur=[...open].sort((x,y)=>(d.get(x)??Infinity)-(d.get(y)??Infinity))[0];open.delete(cur);if(cur===b.id)break;for(const e of roads.edges.filter(e=>e.from===cur&&!e.blocked)){const p=roads.nodes.find(n=>n.id===e.from)?.position,q=roads.nodes.find(n=>n.id===e.to)?.position;if(!p||!q)continue;const w=Math.hypot(p.x-q.x,p.y-q.y)*(1+e.traffic/100),nd=(d.get(cur)??Infinity)+w;if(nd<(d.get(e.to)??Infinity)){d.set(e.to,nd);prev.set(e.to,cur);open.add(e.to)}}}const ids=[b.id];let cur=b.id;while(cur!==a.id&&prev.has(cur)){cur=prev.get(cur)!;ids.push(cur)}ids.reverse();return[from,...ids.map(id=>roads.nodes.find(n=>n.id===id)!.position),to]}
const stationCost={POLICE:75000,FIRE:75000,EMS:65000};
const stationNames={POLICE:'Police Station',FIRE:'Fire Station',EMS:'Rettungswache'};
function build(c:Client,service:Service,name:string,position:MapPoint){const cost=stationCost[service];if(state.center.money<cost)return false;const type=service==='POLICE'?'POLICE_STATION':service==='FIRE'?'FIRE_STATION':'EMS_STATION';const facility:Facility={id:`PLAYER-${c.id}-${Date.now()}`,name:name.slice(0,60),type,position,district:'Player Agency',ownerId:c.id,ownerName:c.name,level:1,upgrades:[]};state.facilities=[...(state.facilities??[]),facility];state.center.money-=cost;state.finance.upgrades+=cost;addVehicle(c,service,position);state.eventLog=[`${formatClock(state.simulationMinutes)} · ${stationNames[service]} · ${c.name} · gebaut`,...state.eventLog].slice(0,20);return true}
function addVehicle(c:Client,service:Service,position:MapPoint){const num=state.units.filter(u=>u.ownerId===c.id&&u.service===service).length+1;const prefix=service==='POLICE'?'RPD':service==='FIRE'?'RFD':'EMS';const model=service==='POLICE'?'Ford Police Interceptor Utility':service==='FIRE'?'Pierce Enforcer Engine':'Ford F-450 Type I Ambulance';const unit:any={id:`${prefix}-${c.id.slice(-4)}-${num}`,callsign:service==='POLICE'?`PATROL ${num}`:service==='FIRE'?`ENGINE ${num}`:`AMBULANCE ${num}`,service,type:service==='POLICE'?'Patrol':service==='FIRE'?'Engine':'ALS Ambulance',status:'AVAILABLE',position:{...position},speed:service==='FIRE'?1.35:service==='EMS'?1.65:1.9,crew:service==='POLICE'?2:3,capabilities:service==='POLICE'?['PATROL','TRAFFIC']:service==='FIRE'?['FIRE_SUPPRESSION','RESCUE']:['ALS','TRANSPORT'],maintenance:100,fuel:100,vehicleModel:model,lightPattern:service==='POLICE'?'DUAL':'TRIPLE',ownerId:c.id,ownerName:c.name};(state.units as any[]).push(unit);return unit}
function upgrade(c:Client,facilityId:string,kind:string){const f=(state.facilities??[]).find(x=>x.id===facilityId) as any;if(!f||f.ownerId!==c.id)return false;const costs:any={FLEET:35000,STAFF:25000,CELLS:30000,APPARATUS:45000,MEDICAL:40000,STORAGE:20000};const cost=costs[kind]??30000;if(state.center.money<cost)return false;state.center.money-=cost;state.finance.upgrades+=cost;f.level=(f.level??1)+1;f.upgrades=[...(f.upgrades??[]),kind];if(kind==='APPARATUS'||kind==='FLEET'||kind==='MEDICAL')addVehicle(c,f.type==='POLICE_STATION'?'POLICE':f.type==='FIRE_STATION'?'FIRE':'EMS',f.position);return true}
function starterIncident(ownerId:string):GameState['incidents'][number]{const definitions:[GameState['incidents'][number]['type'],string,Service[]][]=[['MEDICAL','911 caller reports a person feeling faint inside a residence',['EMS']],['FIRE','911 caller reports smoke coming from a kitchen',['FIRE','EMS']],['POLICE','911 caller reports a suspicious person checking vehicle doors',['POLICE']],['TRAFFIC','911 caller reports a two-vehicle collision with possible injuries',['POLICE','EMS']],['MEDICAL','911 caller reports chest pain and difficulty breathing',['EMS']],['FIRE','911 caller reports an automatic fire alarm with no visible flames',['FIRE']],['POLICE','911 caller reports a loud disturbance outside an apartment building',['POLICE']]];const [type,summary,services]=definitions[Math.floor(Math.random()*definitions.length)];const loc={x:15+Math.random()*70,y:12+Math.random()*76};const priority=(1+Math.floor(Math.random()*3)) as 1|2|3;return{id:`CALL-${String(sequence++).padStart(3,'0')}`,ownerId,type,priority,location:loc,address:['Pine Street','Market Avenue','Canyon Road','Harbor Drive','8th Avenue'][Math.floor(Math.random()*5)]+' '+(100+Math.floor(Math.random()*1800)),status:'NEW',summary,createdAt:Date.now(),ageMinutes:0,stageIndex:0,stages:[summary,'Additional information received','Units responding','Scene stabilized'],requiredServices:services,unitIds:[],patients:type==='MEDICAL'?1:0,escalation:12,danger:type==='FIRE'?35:18,objective:'Notruf aufnehmen, Einsatzort prüfen und passende eigene Kräfte auswählen'} as GameState['incidents'][number]}
function autoGenerate(){const players=[...clients.values()];if(!players.length||Date.now()-lastAutoCall<22000)return false;const active=state.incidents.filter(i=>!['COMPLETE','CANCELLED'].includes(i.status));if(active.length>=10)return false;const p=players[Math.floor(Math.random()*players.length)];const owned=state.incidents.filter(i=>i.ownerId===p.id&&!['COMPLETE','CANCELLED'].includes(i.status));if(owned.length>=5)return false;state.incidents.push(starterIncident(p.id));state.statistics.calls++;state.eventLog=[`${formatClock(state.simulationMinutes)} · NOTRUF EINGEGANGEN · ${p.name}`,...state.eventLog].slice(0,20);lastAutoCall=Date.now();return true}
function acceptCall(c:Client,id:string){const i=state.incidents.find(x=>x.id===id) as any;if(!i||!owns(c,i)||i.status!=='NEW')return false;i.status='DISPATCHING';state.eventLog=[`${formatClock(state.simulationMinutes)} · ${i.id} · Notruf angenommen · ${c.name}`,...state.eventLog].slice(0,20);return true}
function dispatch(c:Client,unitId:string,incidentId:string){const u=state.units.find(x=>x.id===unitId) as any,i=state.incidents.find(x=>x.id===incidentId) as any;if(!u||!i||!owns(c,i)||u.ownerId!==c.id||u.status!=='AVAILABLE'||!i.requiredServices.includes(u.service))return false;u.status='EN_ROUTE';u.target=i.location;u.route=route(u.position,i.location);u.routeIndex=0;u.assignedIncidentId=i.id;i.status='RESPONDING';i.unitIds=[...new Set([...i.unitIds,u.id])];state.eventLog=[`${formatClock(state.simulationMinutes)} · ${u.callsign} → ${i.id}`,...state.eventLog].slice(0,20);return true}
function complete(c:Client,id:string){const i=state.incidents.find(x=>x.id===id) as any;if(!i||!owns(c,i)||i.status==='COMPLETE')return false;i.status='COMPLETE';state.statistics.completed++;state.center.reputation=Math.min(100,state.center.reputation+.35);state.finance.revenueToday+=500+i.priority*180;for(const u of state.units as any[])if(i.unitIds.includes(u.id)&&u.ownerId===c.id){u.status='RETURNING';u.target={x:50,y:50};u.route=route(u.position,u.target);u.routeIndex=0;u.assignedIncidentId=undefined}return true}
function requestAid(c:Client,incidentId:string,toPlayerId:string,requestedServices:Service[],requestedUnits:number,note:string){const target=[...clients.values()].find(p=>p.id===toPlayerId);const i=state.incidents.find(x=>x.id===incidentId) as any;if(!target||target.id===c.id||!owns(c,i))return false;const id=`AID-${Date.now()}-${Math.random().toString(36).slice(2,6)}`;aidRequests.set(id,{id,fromPlayerId:c.id,fromName:c.name,toPlayerId,incidentId,incidentSummary:i.summary,location:i.address,requestedServices,requestedUnits:Math.max(1,Math.min(8,requestedUnits)),note:note.slice(0,180),createdAt:Date.now(),status:'PENDING'});return true}
function answerAid(c:Client,id:string,accept:boolean){const a=aidRequests.get(id);if(!a||a.toPlayerId!==c.id||a.status!=='PENDING')return false;a.status=accept?'ACCEPTED':'DECLINED';if(accept){const candidates=(state.units as any[]).filter(u=>u.ownerId===c.id&&u.status==='AVAILABLE'&&(a.requestedServices.length===0||a.requestedServices.includes(u.service))).slice(0,a.requestedUnits);const i=state.incidents.find(x=>x.id===a.incidentId) as any;if(i)for(const u of candidates){u.status='EN_ROUTE';u.target=i.location;u.route=route(u.position,i.location);u.routeIndex=0;u.assignedIncidentId=i.id;i.unitIds=[...new Set([...i.unitIds,u.id])]}}return true}
function tick(){state.serverTime=Date.now();state.simulationMinutes=(state.simulationMinutes+1)%1440;state.world.hour=Math.floor(state.simulationMinutes/60);state.world.minute=state.simulationMinutes%60;state.world.nightFactor=state.simulationMinutes<360||state.simulationMinutes>1260?1:0;state.world.traffic=Math.max(5,Math.min(98,Math.round(42+Math.sin(state.simulationMinutes/55)*24+(state.world.weather==='RAIN'?13:0))));for(const e of state.roads?.edges??[])e.traffic=Math.max(4,Math.min(99,Math.round(state.world.traffic+Math.sin(state.simulationMinutes/18+Number(e.id.slice(1)))*13)));for(const i of state.incidents){if(i.status==='COMPLETE'||i.status==='CANCELLED')continue;i.ageMinutes+=1/60;i.escalation=Math.min(100,i.escalation+(i.status==='NEW'?.12:.04));if(i.escalation>78&&i.stageIndex<i.stages.length-1){i.stageIndex++;i.summary=i.stages[i.stageIndex]}}for(const u of state.units as any[]){if((u.status!=='EN_ROUTE'&&u.status!=='RETURNING')||!u.route||u.route.length<2)continue;const idx=u.routeIndex??0,next=u.route[Math.min(idx+1,u.route.length-1)],d=Math.hypot(u.position.x-next.x,u.position.y-next.y),step=Math.min(d,(u.speed/10)*(1-state.world.traffic/100*.45));u.heading=Math.atan2(next.y-u.position.y,next.x-u.position.x)*180/Math.PI;if(d<=.7){u.position={...next};u.routeIndex=idx+1;if(u.routeIndex>=u.route.length-1){u.status=u.status==='RETURNING'?'AVAILABLE':'ON_SCENE';u.target=undefined;u.route=undefined;u.routeIndex=undefined}}else{const q=step/d;u.position={x:u.position.x+(next.x-u.position.x)*q,y:u.position.y+(next.y-u.position.y)*q}}}}
const http=createServer((req,res)=>{res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({name:'American Dispatch',status:'online',players:clients.size,facilities:state.facilities?.length??0,path:req.url}))});
const wss=new WebSocketServer({server:http});wss.on('connection',socket=>{if(clients.size>=lobby.maxPlayers){replyError(socket,'Lobby voll');socket.close();return}const c:Client={id:`player-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,name:'Dispatcher',ready:false};clients.set(socket,c);if(!lobby.hostId)lobby.hostId=c.id;socket.send(JSON.stringify({type:'HELLO_ACK',playerId:c.id}));socket.send(JSON.stringify(snapshot()));broadcastAid();socket.on('message',raw=>{try{const m=JSON.parse(raw.toString()) as any;let changed=false;if(m.type==='HELLO'){c.name=typeof m.name==='string'?m.name.slice(0,32):c.name;c.ready=m.ready===true;socket.send(JSON.stringify({type:'HELLO_ACK',playerId:c.id,role:'PLAYER'}));changed=true}else if(m.type==='BUILD_FACILITY'&&['POLICE','FIRE','EMS'].includes(m.service)&&m.position){const service=m.service as Service;changed=build(c,service,m.name??stationNames[service],m.position)}else if(m.type==='UPGRADE_FACILITY')changed=upgrade(c,m.facilityId,m.upgrade);else if(m.type==='ACCEPT_CALL')changed=acceptCall(c,m.incidentId);else if(m.type==='DISPATCH')changed=dispatch(c,m.unitId,m.incidentId);else if(m.type==='COMPLETE')changed=complete(c,m.incidentId);else if(m.type==='REQUEST_MUTUAL_AID')changed=requestAid(c,m.incidentId,m.toPlayerId,m.requestedServices??[],m.requestedUnits??1,m.note??'');else if(m.type==='ANSWER_MUTUAL_AID')changed=answerAid(c,m.requestId,!!m.accept);else if(m.type==='PING'){socket.send(JSON.stringify({type:'PONG',serverTime:Date.now()}));return}else{replyError(socket,'Unbekannte Aktion');return}if(changed)persist();broadcast(snapshot());if(m.type==='REQUEST_MUTUAL_AID'||m.type==='ANSWER_MUTUAL_AID')broadcastAid()}catch{replyError(socket,'Ungültige Nachricht')}});socket.on('close',()=>{clients.delete(socket);if(lobby.hostId===c.id)lobby.hostId=clients.values().next().value?.id??'';broadcast(snapshot());broadcastAid()})});
setInterval(()=>{const changed=autoGenerate();tick();if(changed||Math.random()<.35)persist();broadcast(snapshot())},1000);setInterval(persist,30000);const port=Number(process.env.PORT??8787);http.listen(port,()=>console.log(`American Dispatch server listening on :${port}`));