import { createServer } from 'node:http';
import { mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { WebSocketServer, type WebSocket } from 'ws';
import { cloneState, formatClock, type GameState, type Role, type MapPoint, type RoadNode } from '../src/game/state';

const roles:Role[]=['CALL_TAKER','POLICE_DISPATCHER','FIRE_DISPATCHER','EMS_DISPATCHER','SUPERVISOR','MANAGER','ADMIN'];
const dispatchToken=process.env.DISPATCH_TOKEN; const adminToken=process.env.ADMIN_TOKEN;
const savePath=resolve(process.env.SAVE_FILE??'data/game-state.json');
const clients=new Map<WebSocket,{id:string;name:string;role:Role;ready:boolean}>();
let lobby={id:'REDWOOD-1',name:'Redwood Metro Multiplayer',hostId:'',players:[] as Array<{id:string;name:string;role:Role;ready:boolean;connected:boolean}>,maxPlayers:8};
function validState(v:unknown):v is GameState{const c=v as Partial<GameState>|null;return !!c&&c.version===2&&Array.isArray(c.units)&&Array.isArray(c.incidents)&&!!c.center&&!!c.world}
function load(){try{const v=JSON.parse(readFileSync(savePath,'utf8')) as unknown;if(validState(v))return v}catch{}return cloneState()}
let state=load(); let sequence=Math.max(0,...state.incidents.map(i=>Number(i.id.replace('INC-',''))||0))+1;
function persist(){try{mkdirSync(dirname(savePath),{recursive:true});const tmp=savePath+'.tmp';writeFileSync(tmp,JSON.stringify(state),'utf8');renameSync(tmp,savePath)}catch(e){console.error('persist',e)}}
function broadcast(v:unknown){const p=JSON.stringify(v);for(const s of clients.keys())if(s.readyState===s.OPEN)s.send(p)}
function syncLobby(){lobby.players=[...clients.values()].map(p=>({id:p.id,name:p.name,role:p.role,ready:p.ready,connected:true}))}
function snapshot(){syncLobby();return {type:'STATE_SNAPSHOT',payload:state,lobby}}
function error(s:WebSocket,m:string){s.send(JSON.stringify({type:'ERROR',message:m}))}
function auth(c:{role:Role},r:Role[]){return r.includes(c.role)}
function roleFor(r:unknown,t:unknown,a:unknown):Role{if(!roles.includes(r as Role))return 'CALL_TAKER';if(r==='ADMIN')return adminToken&&a===adminToken?'ADMIN':'CALL_TAKER';return dispatchToken&&t===dispatchToken?r as Role:'CALL_TAKER'}
function nearest(p:MapPoint){return (state.roads?.nodes??[]).reduce<RoadNode|null>((b,n)=>!b||Math.hypot(n.position.x-p.x,n.position.y-p.y)<Math.hypot(b.position.x-p.x,b.position.y-p.y)?n:b,null)}
function route(from:MapPoint,to:MapPoint){const r=state.roads;if(!r)return[from,to];const a=nearest(from),b=nearest(to);if(!a||!b)return[from,to];const d=new Map<string,number>(),prev=new Map<string,string>();const open=new Set<string>([a.id]);for(const n of r.nodes)d.set(n.id,Infinity);d.set(a.id,0);while(open.size){const cur=[...open].sort((x,y)=>(d.get(x)??Infinity)-(d.get(y)??Infinity))[0];open.delete(cur);if(cur===b.id)break;for(const e of r.edges.filter(e=>e.from===cur&&!e.blocked)){const p=r.nodes.find(n=>n.id===e.from)!.position,q=r.nodes.find(n=>n.id===e.to)!.position;const w=Math.hypot(p.x-q.x,q.y-p.y)*(1+e.traffic/100);const nd=(d.get(cur)??Infinity)+w;if(nd<(d.get(e.to)??Infinity)){d.set(e.to,nd);prev.set(e.to,cur);open.add(e.to)}}}const ids:string[]=[];let at=b.id;ids.push(at);while(at!==a.id&&prev.has(at)){at=prev.get(at)!;ids.push(at)}ids.reverse();return[from,...ids.map(id=>r.nodes.find(n=>n.id===id)!.position),to]}
function dispatch(c:{role:Role},unitId:string,incidentId:string){if(!auth(c,['SUPERVISOR','POLICE_DISPATCHER','FIRE_DISPATCHER','EMS_DISPATCHER','ADMIN']))return false;const u=state.units.find(x=>x.id===unitId),i=state.incidents.find(x=>x.id===incidentId);if(!u||!i||u.status!=='AVAILABLE')return false;if(c.role==='POLICE_DISPATCHER'&&u.service!=='POLICE'||c.role==='FIRE_DISPATCHER'&&u.service!=='FIRE'||c.role==='EMS_DISPATCHER'&&u.service!=='EMS')return false;u.status='EN_ROUTE';u.target=i.location;u.route=route(u.position,i.location);u.routeIndex=0;u.assignedIncidentId=i.id;i.status='RESPONDING';i.unitIds=[...new Set([...i.unitIds,u.id])];state.eventLog=[`${formatClock(state.simulationMinutes)} · ${u.callsign} → ${i.id} · ROUTING AKTIV`,...state.eventLog].slice(0,20);return true}
function complete(c:{role:Role},id:string){if(!auth(c,['SUPERVISOR','ADMIN','EMS_DISPATCHER','FIRE_DISPATCHER','POLICE_DISPATCHER']))return false;const i=state.incidents.find(x=>x.id===id);if(!i||i.status==='COMPLETE'||i.status==='CANCELLED')return false;i.status='COMPLETE';state.statistics.completed++;if(i.type==='MEDICAL'||i.type==='MCI')state.statistics.patientsSaved=(state.statistics.patientsSaved??0)+Math.max(1,Math.round(i.patients*.7));if(i.type==='FIRE'||i.type==='MASS_FIRE')state.statistics.firesControlled++;state.center.reputation=Math.min(100,state.center.reputation+.35);state.finance.revenueToday+=500+i.priority*180;for(const u of state.units)if(i.unitIds.includes(u.id)){u.status='RETURNING';u.route=route(u.position,{x:50,y:50});u.routeIndex=0;u.target={x:50,y:50};u.assignedIncidentId=undefined}return true}
function generate(c:{role:Role}){if(!auth(c,['SUPERVISOR','CALL_TAKER','ADMIN']))return false;const types:[GameState['incidents'][number]['type'],string,Role[]][]=[['MEDICAL','Bewusstlose Person',['EMS_DISPATCHER']],['FIRE','Wohnungsbrand',['FIRE_DISPATCHER']],['POLICE','Einbruch',['POLICE_DISPATCHER']],['TRAFFIC','Schwerer Verkehrsunfall',['POLICE_DISPATCHER','EMS_DISPATCHER']],['HAZMAT','Gefahrstoffaustritt',['FIRE_DISPATCHER','POLICE_DISPATCHER','EMS_DISPATCHER']],['WILDFIRE','Vegetationsbrand',['FIRE_DISPATCHER','EMS_DISPATCHER']],['MCI','Massenanfall Verletzter',['FIRE_DISPATCHER','EMS_DISPATCHER','POLICE_DISPATCHER']],['FLOOD','Überflutung',['FIRE_DISPATCHER','EMS_DISPATCHER']],['MASS_FIRE','Großbrand im Industriegebiet',['FIRE_DISPATCHER','EMS_DISPATCHER','POLICE_DISPATCHER']],['ACTIVE_THREAT','Amok-/Bedrohungslage',['POLICE_DISPATCHER','EMS_DISPATCHER']]];const [type,name]=types[Math.floor(Math.random()*types.length)];const id=`INC-${1050+sequence++}`,location={x:12+Math.random()*76,y:10+Math.random()*80};const major=['MCI','MASS_FIRE','ACTIVE_THREAT'].includes(type);state.incidents.push({id,type,priority:(major?1:1+Math.floor(Math.random()*3)) as 1|2|3,location,address:['Pine Street','Market Avenue','Canyon Road','Harbor Drive','8th Avenue'][Math.floor(Math.random()*5)]+' '+(100+Math.floor(Math.random()*1800)),status:'NEW',summary:name,createdAt:Date.now(),ageMinutes:0,stageIndex:0,stages:major?[name,'Großlage erkannt','Einsatzleitung etabliert','Lage stabilisiert']:[name,'Weitere Kräfte erforderlich','Lage stabilisiert'],requiredServices:type==='POLICE'||type==='ACTIVE_THREAT'?['POLICE']:type==='FIRE'||type==='WILDFIRE'||type==='MASS_FIRE'?['FIRE','EMS']:type==='MCI'?['FIRE','EMS','POLICE']:['EMS'],unitIds:[],patients:type==='MCI'?15+Math.floor(Math.random()*30):type==='MEDICAL'?1+Math.floor(Math.random()*3):0,escalation:major?55:20+Math.random()*30,danger:major?75:20+Math.random()*65,objective:major?'Einsatzleitung aufbauen, Abschnitte bilden und Ressourcen koordinieren':'Lage bewerten und passende Einheiten disponieren',commandPost:major?{x:location.x+3,y:location.y+2}:undefined,sections:major?[{id:'SEC-A',name:'Triage / Rettung',objective:'Verletzte versorgen',unitIds:[]},{id:'SEC-B',name:'Sicherung',objective:'Gefahrenbereich sichern',unitIds:[]}]:undefined});state.statistics.calls++;state.eventLog=[`${formatClock(state.simulationMinutes)} · ${id} · ${major?'GROSSLAGE':'Neuer 911-Einsatz'}`,...state.eventLog].slice(0,20);return true}
function tick(){state.serverTime=Date.now();state.simulationMinutes=(state.simulationMinutes+1)%1440;state.world.hour=Math.floor(state.simulationMinutes/60);state.world.minute=state.simulationMinutes%60;state.world.nightFactor=(state.simulationMinutes<360||state.simulationMinutes>1260)?1:0;state.world.traffic=Math.max(5,Math.min(98,Math.round(42+Math.sin(state.simulationMinutes/55)*24+(state.world.weather==='RAIN'?13:0)-(state.world.nightFactor??0)*15)));state.world.eventRate=1+state.world.traffic/150;for(const e of state.roads?.edges??[]){e.traffic=Math.max(4,Math.min(99,Math.round(state.world.traffic+Math.sin(state.simulationMinutes/18+Number(e.id.slice(1)))*13)));if(e.traffic>92)e.blocked=Math.random()<.01}for(const i of state.incidents){if(i.status==='COMPLETE'||i.status==='CANCELLED')continue;i.ageMinutes+=1/60;i.escalation=Math.min(100,i.escalation+(i.status==='NEW'?.12:.04));if(i.escalation>78&&i.stageIndex<i.stages.length-1){i.stageIndex++;i.summary=i.stages[i.stageIndex];i.priority=Math.max(1,i.priority-1) as 1|2|3|4;state.eventLog=[`${formatClock(state.simulationMinutes)} · ${i.id} · LAGE ESKALIERT`,...state.eventLog].slice(0,20)}}for(const u of state.units){if((u.status!=='EN_ROUTE'&&u.status!=='RETURNING')||!u.route||u.route.length<2)continue;const idx=u.routeIndex??0,next=u.route[Math.min(idx+1,u.route.length-1)],d=Math.hypot(u.position.x-next.x,u.position.y-next.y);u.heading=Math.atan2(next.y-u.position.y,next.x-u.position.x)*180/Math.PI;const step=Math.min(d,(u.speed/10)*(1-state.world.traffic/100*.45));if(d<=.7){u.position={...next};u.routeIndex=idx+1;if(u.routeIndex>=u.route.length-1){u.status=u.status==='RETURNING'?'AVAILABLE':'ON_SCENE';u.target=undefined;u.route=undefined;u.routeIndex=undefined}}else{const q=step/d;u.position={x:u.position.x+(next.x-u.position.x)*q,y:u.position.y+(next.y-u.position.y)*q}}u.fuel=Math.max(0,u.fuel-step*.06);u.maintenance=Math.max(0,u.maintenance-.003)}for(const p of state.personnel)if(p.active){p.fatigue=Math.min(100,(p.fatigue??0)+.015);p.stress=Math.min(100,p.stress+(state.world.nightFactor?0.006:0.002))}state.finance.costsToday+=2+state.units.length*.16}
const http=createServer((req,res)=>{res.writeHead(200,{'content-type':'application/json; charset=utf-8'});res.end(JSON.stringify({name:'American Dispatch',region:state.center.region,version:state.version,players:clients.size,status:'online',roads:state.roads?.edges.length??0,incidents:state.incidents.length,path:req.url}))});
const wss=new WebSocketServer({server:http});wss.on('connection',socket=>{if(clients.size>=lobby.maxPlayers){error(socket,'Lobby voll');socket.close();return}const client={id:`player-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,name:'Dispatcher',role:'CALL_TAKER' as Role,ready:false};clients.set(socket,client);if(!lobby.hostId)lobby.hostId=client.id;socket.send(JSON.stringify(snapshot()));socket.on('message',raw=>{try{const m=JSON.parse(raw.toString()) as Record<string,unknown>;let changed=false;if(m.type==='HELLO'){client.name=typeof m.name==='string'?m.name.slice(0,32):client.name;client.role=roleFor(m.role,m.token,m.adminToken);client.ready=m.ready===true}else if(m.type==='READY'){client.ready=Boolean(m.ready)}else if(m.type==='DISPATCH'&&typeof m.unitId==='string'&&typeof m.incidentId==='string')changed=dispatch(client,m.unitId,m.incidentId);else if(m.type==='COMPLETE'&&typeof m.incidentId==='string')changed=complete(client,m.incidentId);else if(m.type==='GENERATE_INCIDENT')changed=generate(client);else if(m.type==='SET_WEATHER'&&auth(client,['ADMIN'])&&typeof m.weather==='string'){const allowed=['CLEAR','CLOUDY','RAIN','HEAVY_RAIN','THUNDERSTORM','FOG','SNOW','HEATWAVE','WINDSTORM','FLOODING'];if(allowed.includes(m.weather)){state.world.weather=m.weather as GameState['world']['weather'];changed=true}}else if(m.type==='SET_TIME'&&auth(client,['ADMIN'])&&Number.isInteger(m.minutes)&&Number(m.minutes)>=0&&Number(m.minutes)<1440){state.simulationMinutes=Number(m.minutes);changed=true}else if(m.type==='RELEASE_UNITS'&&auth(client,['ADMIN'])){state.units.forEach(u=>{u.status='AVAILABLE';u.target=undefined;u.route=undefined;u.routeIndex=undefined;u.assignedIncidentId=undefined});changed=true}else if(m.type==='ADD_BUDGET'&&auth(client,['ADMIN'])){state.center.money+=50000;changed=true}else if(m.type==='RESET_GAME'&&auth(client,['ADMIN'])){state=cloneState();sequence=Math.max(0,...state.incidents.map(i=>Number(i.id.replace('INC-',''))||0))+1;changed=true}else if(m.type==='PING'){socket.send(JSON.stringify({type:'PONG',serverTime:Date.now()}));return}else{error(socket,'Unbekannte oder unvollständige Aktion');return}syncLobby();if(changed)persist();broadcast(snapshot())}catch{error(socket,'Ungültige Nachricht')}});socket.on('close',()=>{clients.delete(socket);syncLobby();if(lobby.hostId===client.id)lobby.hostId=lobby.players[0]?.id??'';broadcast(snapshot())})});
setInterval(()=>{tick();broadcast(snapshot())},1000);setInterval(persist,30000);const port=Number(process.env.PORT??8787);http.listen(port,()=>console.log(`American Dispatch server listening on :${port}`));
