import { useEffect, useMemo, useState } from 'react';
import { cloneState, getIncidentStatusLabel, type GameState, type Role, type Service, type Unit } from './game/state';
import { play911Incoming, playDispatchAlert, playMutualAid, playRadioPing, playSiren, toggleAmbient } from './game/audio';
import { RealMapView } from './ui/RealMapView';
import './styles.css';
import './rebuild.css';

type Screen='MENU'|'GAME';
type Tab='CAD'|'AGENCY'|'RANKS'|'WORLD';
const roles:Record<Role,string>={CALL_TAKER:'911 Call Taker',POLICE_DISPATCHER:'Police Dispatcher',FIRE_DISPATCHER:'Fire Dispatcher',EMS_DISPATCHER:'EMS Dispatcher',SUPERVISOR:'Supervisor',MANAGER:'Manager',ADMIN:'Administrator'};
const meta:Record<Service,{name:string;station:string;color:string}>= {POLICE:{name:'Police Department',station:'Police Station',color:'#58a6ff'},FIRE:{name:'Fire Department',station:'Fire Station',color:'#ff5d5d'},EMS:{name:'Emergency Medical Services',station:'EMS Station',color:'#43d7a2'}};
const ranks:Record<Service,string[]>={POLICE:['Cadet','Police Officer','Senior Officer','Sergeant','Lieutenant','Captain','Commander','Deputy Chief','Chief'],FIRE:['Firefighter Recruit','Firefighter','Driver/Engineer','Lieutenant','Captain','Battalion Chief','Division Chief','Deputy Chief','Fire Chief'],EMS:['EMT Trainee','EMT','Advanced EMT','Paramedic','Field Supervisor','Operations Supervisor','Division Chief','Deputy Director','EMS Director']};
const serverUrl=import.meta.env.VITE_SERVER_URL??`${location.protocol==='https:'?'wss':'ws'}://${location.hostname}:8787`;
let ws:WebSocket|null=null;
function loadProfile(){try{return JSON.parse(localStorage.getItem('ad-profile-v3')??'null')}catch{return null}}
function persist(p:unknown){localStorage.setItem('ad-profile-v3',JSON.stringify(p))}
function cash(v:number){return `$${Math.max(0,Math.round(v)).toLocaleString('en-US')}`}
function dist(a:{x:number;y:number},b:{x:number;y:number}){return Math.hypot(a.x-b.x,a.y-b.y)}
function capability(type:string,level:number){if(level>=5)return true;return !['MCI','ACTIVE_THREAT','MASS_FIRE','HAZMAT'].includes(type)}

export default function App(){
 const saved=loadProfile();
 const [profile,setProfile]=useState<any>(()=>saved??{started:false,service:'FIRE',level:1,xp:0,money:100000,station:false,playerName:'Dispatcher'});
 const [screen,setScreen]=useState<Screen>('MENU');
 const [game,setGame]=useState<GameState>(()=>cloneState());
 const [connected,setConnected]=useState(false); const [playerId,setPlayerId]=useState('');
 const [aid,setAid]=useState<any[]>([]); const [service,setService]=useState<Service>(()=>saved?.service??'FIRE');
 const [role,setRole]=useState<Role>('CALL_TAKER'); const [tab,setTab]=useState<Tab>('CAD'); const [selected,setSelected]=useState(''); const [filter,setFilter]=useState<'ALL'|Service>('ALL'); const [zoom,setZoom]=useState(1); const [notice,setNotice]=useState('');
 const currentService=profile.service as Service; const rank=ranks[currentService][Math.min(8,Math.max(0,profile.level-1))];
 const active=game.incidents.filter(i=>i.status!=='COMPLETE'&&i.status!=='CANCELLED'&&capability(i.type,profile.level));
 const incident=game.incidents.find(i=>i.id===selected)??active[0];
 const myUnits:Unit[]=profile.station&&playerId?game.units.filter((u:any)=>u.ownerId===playerId&&u.service===currentService):[];
 const otherPlayers=useMemo(()=>game?((game as any).__lobby?.players??[]):[],[game]);
 const incomingAid=aid.filter(a=>a.toPlayerId===playerId&&a.status==='PENDING');
 const outgoingAid=aid.filter(a=>a.fromPlayerId===playerId&&a.status==='PENDING');
 function send(m:unknown){if(ws?.readyState===WebSocket.OPEN){ws.send(JSON.stringify(m));return true}return false}
 useEffect(()=>{if(screen!=='GAME')return;try{ws=new WebSocket(serverUrl);ws.onopen=()=>{setConnected(true);ws?.send(JSON.stringify({type:'HELLO',name:profile.playerName,role}))};ws.onclose=()=>{setConnected(false);ws=null};ws.onerror=()=>setConnected(false);ws.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.type==='HELLO_ACK'&&m.playerId)setPlayerId(m.playerId);if(m.type==='STATE_SNAPSHOT'&&m.payload){const next=m.payload as GameState;(next as any).__lobby=m.lobby;setGame(next)}if(m.type==='MUTUAL_AID_SNAPSHOT')setAid(m.payload??[]);if(m.type==='ERROR')setNotice(m.message??'Server error')}catch{setNotice('Ungültige Serverantwort')}}}catch{setConnected(false)}return()=>{ws?.close();ws=null}},[screen]);
 useEffect(()=>{if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type:'HELLO',name:profile.playerName,role}))},[role,profile.playerName]);
 useEffect(()=>{const t=setInterval(()=>{if(!connected)setGame(s=>{const n=structuredClone(s);n.serverTime=Date.now();n.simulationMinutes=(n.simulationMinutes+1)%1440;n.world.hour=Math.floor(n.simulationMinutes/60);n.world.minute=n.simulationMinutes%60;return n})},1000);return()=>clearInterval(t)},[connected]);
 useEffect(()=>{if(active.length&&(!selected||!active.some(i=>i.id===selected)))setSelected(active[0].id)},[active,selected]);
 useEffect(()=>{if(active.some(i=>i.status==='NEW'))play911Incoming()},[active.length]);
 function openGame(){setScreen('GAME');setTab('CAD');setNotice('Willkommen in Redwood Metro. Baue zuerst deine eigene Station.')}
 function build(){if(profile.station)return;if(profile.money<75000){setNotice('Nicht genug Startkapital. Benötigt: $75,000.');return}const p={...profile,started:true,station:true,money:profile.money-75000,xp:100};setProfile(p);persist(p);setService(currentService);send({type:'BUILD_FACILITY',service:currentService,name:`${meta[currentService].name} Station`,position:{x:43+Math.random()*12,y:48+Math.random()*10}});playDispatchAlert();setNotice(`${meta[currentService].station} gebaut. ${currentService==='FIRE'?'Fire ist für den Start besonders gut geeignet.':''}`)}
 function changeService(s:Service){if(profile.station){setNotice('Die erste Station ist bereits gebaut. Weitere Services werden später als Ausbau freigeschaltet.');return}const p={...profile,service:s};setProfile(p);persist(p);setService(s)}
 function takeCall(){if(!incident||incident.status!=='NEW')return;if(send({type:'ACCEPT_CALL',incidentId:incident.id})){playRadioPing();setNotice(`${incident.id}: 911-Anruf aufgenommen. Angaben prüfen und an die passende Disposition geben.`);return}setNotice('Der 911-Server ist nicht verbunden.')}
 function dispatch(u:Unit){if(!incident||u.status!=='AVAILABLE')return;if(send({type:'DISPATCH',unitId:u.id,incidentId:incident.id})){playRadioPing();return}setNotice('Keine Serververbindung – Dispatch nicht bestätigt.')}
 function auto(){const u=myUnits.filter(u=>u.status==='AVAILABLE').sort((a,b)=>incident?dist(a.position,incident.location)-dist(b.position,incident.location):0)[0];if(u)dispatch(u);else setNotice('Keine verfügbare eigene Einheit.')}
 function complete(){if(!incident)return;if(send({type:'COMPLETE',incidentId:incident.id})){const xp=profile.xp+100;const p={...profile,xp,level:Math.min(9,1+Math.floor(xp/500)),money:profile.money+500};setProfile(p);persist(p);playDispatchAlert();return}setNotice('Der Einsatz konnte nicht bestätigt werden.')}
 function requestAid(){if(!incident){setNotice('Kein Einsatz ausgewählt.');return}const target=otherPlayers.find((p:any)=>p.id!==playerId);if(!target){setNotice('Keine andere Leitstelle ist aktuell online.');return}const services=incident.requiredServices.length?incident.requiredServices:[currentService];if(send({type:'REQUEST_MUTUAL_AID',incidentId:incident.id,toPlayerId:target.id,requestedServices:services,requestedUnits:1,note:`Mutual Aid benötigt für ${incident.id}.`})){playMutualAid();setNotice(`CAD-to-CAD Anfrage an ${target.name} gesendet.`)}else setNotice('CAD-to-CAD konnte nicht gesendet werden.')}
 function answerAid(id:string,accept:boolean){if(send({type:'ANSWER_MUTUAL_AID',requestId:id,accept})){playMutualAid();setNotice(accept?'Mutual Aid angenommen. Verfügbare Einheiten werden entsendet.':'Mutual Aid abgelehnt.')}}
 function backMenu(){setScreen('MENU')}
 if(screen==='MENU')return <main className="rebuild-menu"><div className="menu-grid"/><section className="menu-content"><div className="menu-kicker"><i/>LIVE PUBLIC SAFETY SIMULATION</div><h1>AMERICAN<br/><strong>DISPATCH</strong></h1><p>American-style 911 · separate player CADs · mutual aid · real-world map</p><button className="hero-button" onClick={openGame}>PLAY <span>→</span></button><div className="menu-options"><button onClick={()=>setNotice('Profil: Name und Karriere werden lokal auf diesem Gerät gespeichert.')}>PROFILE</button><button onClick={()=>setNotice('Einstellungen: Audio und Darstellung werden direkt im CAD gesteuert.')}>SETTINGS</button><button onClick={()=>setNotice('Errungenschaften werden mit Karrierefortschritt freigeschaltet.')}>ACHIEVEMENTS</button></div><div className="menu-status"><span><i/>SERVER READY</span><span>REDWOOD METRO · USA</span><span>BUILD 3.0</span></div>{notice&&<div className="toast">{notice}</div>}</section><footer>MAP DATA © OPENSTREETMAP CONTRIBUTORS · OPENFREEMAP</footer></main>;
 return <main className="rebuild-game"><header className="game-top"><button className="brand-mini" onClick={backMenu}><span>911</span><b>AMERICAN DISPATCH</b></button><div className="agency"><strong>{meta[currentService].name}</strong><small>{rank.toUpperCase()} · LEVEL {profile.level}</small></div><div className="top-stats"><span><small>XP</small><b>{profile.xp%500}/500</b></span><span><small>BUDGET</small><b>{cash(profile.money)}</b></span><span><small>911</small><b>{game.statistics.calls}</b></span><span><small>CAD</small><b className={connected?'online':'offline'}>{connected?'ONLINE':'OFFLINE'}</b></span></div></header><nav className="game-tabs">{(['CAD','AGENCY','RANKS','WORLD'] as Tab[]).map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}<select value={role} onChange={e=>setRole(e.target.value as Role)}>{Object.entries(roles).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></nav>
 {tab==='CAD'&&<section className="cad-grid"><aside className="cad-panel calls"><div className="panel-title"><span>911 CALL QUEUE</span><b>{active.length}</b></div><div className="filter-row"><button className={filter==='ALL'?'active':''} onClick={()=>setFilter('ALL')}>ALL</button>{(['POLICE','FIRE','EMS'] as Service[]).map(s=><button key={s} className={filter===s?'active':''} onClick={()=>setFilter(s)}>{s}</button>)}</div><div className="call-list">{active.filter(i=>filter==='ALL'||i.requiredServices.includes(filter)).map(i=><button key={i.id} className={selected===i.id?'call selected':'call'} onClick={()=>setSelected(i.id)}><strong>{i.id}</strong><span>{i.status==='NEW'?'☎ INCOMING 911':getIncidentStatusLabel(i.status)} · P{i.priority}</span><small>{i.address}</small><em>{i.summary}</em><label>{i.type} · {i.requiredServices.join(' + ')}</label></button>)}</div><div className="call-actions">{incident?.status==='NEW'&&<button className="dispatch-new" onClick={takeCall}>☎ TAKE 911 CALL</button>}{incident&&incident.status!=='NEW'&&<div className="call-processed">✓ CALL PROCESSED · SEND TO {incident.requiredServices.join(' / ')}</div>}</div><div className="aid-mini"><b>CAD-TO-CAD</b><span>{incomingAid.length} incoming · {outgoingAid.length} outgoing</span>{incomingAid.map(a=><div key={a.id} className="aid-request"><strong>REQUEST FROM {a.fromName}</strong><small>{a.incidentSummary}</small><button onClick={()=>answerAid(a.id,true)}>ACCEPT</button><button onClick={()=>answerAid(a.id,false)}>DECLINE</button></div>)}</div></aside><div className="map-stage"><RealMapView state={game} zoom={zoom} onZoomChange={setZoom} onIncidentSelect={setSelected}/><div className="map-banner"><b>{currentService} DISPATCH</b><span>{rank} · LEVEL {profile.level}</span><span>{game.world.traffic}% TRAFFIC</span></div>{!profile.station&&<div className="build-overlay"><b>YOUR CAD IS NOT DEPLOYED</b><span>Build your first station to receive and dispatch your own resources.</span><button onClick={()=>setTab('AGENCY')}>BUILD AGENCY</button></div>}</div><aside className="cad-panel units"><div className="panel-title"><span>YOUR UNITS</span><b>{myUnits.length}</b></div>{!profile.station?<div className="locked"><strong>NO STATION</strong><p>Your organization has no deployed units yet.</p><button onClick={()=>setTab('AGENCY')}>BUILD FIRST STATION</button></div>:<>{myUnits.map(u=><button className="unit-row" key={u.id} onClick={()=>dispatch(u)}><span className={`unit-dot ${u.service.toLowerCase()}`}/><div><b>{u.callsign}</b><small>{u.vehicleModel??u.type}</small></div><em>{u.status}</em></button>)}<button className="auto" onClick={auto}>AUTO DISPATCH</button>{incident&&incident.status!=='NEW'&&<button className="mutual-aid-button" onClick={requestAid}>REQUEST MUTUAL AID</button>}<div className="selected-actions">{incident&&<><strong>{incident.id}</strong><span>{incident.objective}</span><button onClick={complete}>COMPLETE INCIDENT</button></>}</div></>}</aside></section>}
 {tab==='AGENCY'&&<section className="agency-page"><div className="agency-card"><small>YOUR ORGANIZATION</small><h2>{meta[currentService].name}</h2><div className="rank-display"><b>LEVEL {profile.level}</b><strong>{rank}</strong><span>{profile.xp} XP · {cash(profile.money)}</span></div>{!profile.station?<><p>You begin with no deployed station. Choose your first discipline and build it for <b>$75,000</b>. Fire is recommended for a strong early economy and manageable starter calls.</p><div className="service-pills">{(['FIRE','POLICE','EMS'] as Service[]).map(s=><button key={s} className={currentService===s?'active':''} onClick={()=>changeService(s)}>{meta[s].station}{s==='FIRE'&&<small>RECOMMENDED</small>}</button>)}</div><button className="build" onClick={build}>BUILD {meta[currentService].station.toUpperCase()} · $75,000</button></>:<div className="built"><i>✓</i><div><b>{meta[currentService].station} operational</b><span>Owner CAD: {profile.playerName} · {myUnits.length} deployed unit</span></div></div>}</div><div className="unlock-card"><small>STARTER CAPABILITY</small><div><b>LEVEL 1</b><span>Medical calls, small fires, alarms, disturbances and minor collisions</span></div><div><b>LEVEL 3</b><span>More complex incidents and additional fleet options</span></div><div><b>LEVEL 5</b><span>MCI, HazMat, active threats and major multi-agency events</span></div></div><div className="aid-card"><small>CAD-TO-CAD MUTUAL AID</small><h3>Separate organizations. Shared emergency support.</h3><p>Other players keep their own budgets, stations and units. When you are short on resources, request specific help directly from another CAD.</p>{otherPlayers.filter((p:any)=>p.id!==playerId).map((p:any)=><div key={p.id} className="player-row"><b>{p.name}</b><span>{roles[p.role as Role]??p.role}</span><button onClick={requestAid}>REQUEST</button></div>)}{otherPlayers.filter((p:any)=>p.id!==playerId).length===0&&<div className="empty">No other CAD currently connected.</div>}</div></section>}
 {tab==='RANKS'&&<section className="ranks-page"><div><small>CAREER PROGRESSION</small><h2>YOUR RANKS</h2><p>Your agency grows from a small local operation into a fully staffed public-safety organization. Incident complexity follows capability.</p></div><div className="rank-grid">{ranks[currentService].map((r,i)=><article className={i<profile.level?'current':''} key={r}><small>LEVEL {i+1}</small><h3>{r}</h3><p>{i<2?'Starter operations':i<4?'Core operations and fleet':i<6?'Supervision and expansion':i<8?'Special operations':'Executive command'}</p></article>)}</div></section>}
 {tab==='WORLD'&&<section className="world-page"><div><small>MULTIPLAYER WORLD</small><h2>REDWOOD METRO</h2><p>One real-world map. Separate CADs. Automatic 911 traffic. Player organizations only interact when they deliberately exchange mutual aid.</p></div><div className="world-stats"><b>{game.facilities?.length??0}<small>FACILITIES</small></b><b>{game.units.length}<small>VISIBLE UNITS</small></b><b>{active.length}<small>ACTIVE 911</small></b><b>{(game as any).__lobby?.players?.length??0}<small>CONNECTED CADS</small></b></div></section>}
 <div className="game-audio"><button onClick={()=>toggleAmbient()}>♫ AMBIENT</button><button onClick={playRadioPing}>RADIO</button><button onClick={playSiren}>SIREN</button></div>{notice&&<div className="toast game-toast">{notice}<button onClick={()=>setNotice('')}>×</button></div>}</main>;
}
