import { useEffect, useState } from 'react';
import { cloneState, getIncidentStatusLabel, type GameState, type Role, type Service, type Unit } from './game/state';
import { RealMapView } from './ui/RealMapView';
import './styles.css';
import './rebuild.css';

type Screen='MENU'|'SERVICE'|'GAME';
type Tab='CAD'|'AGENCY'|'RANKS'|'WORLD';
const roles:Record<Role,string>={CALL_TAKER:'911 Call Taker',POLICE_DISPATCHER:'Police Dispatcher',FIRE_DISPATCHER:'Fire Dispatcher',EMS_DISPATCHER:'EMS Dispatcher',SUPERVISOR:'Supervisor',MANAGER:'Manager',ADMIN:'Administrator'};
const meta:Record<Service,{name:string;station:string;color:string}>= {POLICE:{name:'Police Department',station:'Police Station',color:'#58a6ff'},FIRE:{name:'Fire Department',station:'Fire Station',color:'#ff5d5d'},EMS:{name:'Emergency Medical Services',station:'EMS Station',color:'#43d7a2'}};
const ranks:Record<Service,string[]>={POLICE:['Cadet','Police Officer','Senior Officer','Sergeant','Lieutenant','Captain','Commander','Deputy Chief','Chief'],FIRE:['Firefighter Recruit','Firefighter','Driver/Engineer','Lieutenant','Captain','Battalion Chief','Division Chief','Deputy Chief','Fire Chief'],EMS:['EMT Trainee','EMT','Advanced EMT','Paramedic','Field Supervisor','Operations Supervisor','Division Chief','Deputy Director','EMS Director']};
const serverUrl=import.meta.env.VITE_SERVER_URL??`${location.protocol==='https:'?'wss':'ws'}://${location.hostname}:8787`;
let ws:WebSocket|null=null;
const token=new URLSearchParams(location.search).get('token')??undefined;
function loadProfile(){try{return JSON.parse(localStorage.getItem('ad-profile-v2')??'null')}catch{return null}}
function persist(p:unknown){localStorage.setItem('ad-profile-v2',JSON.stringify(p))}
function cash(v:number){return `$${Math.round(v).toLocaleString('en-US')}`}
function dist(a:{x:number;y:number},b:{x:number;y:number}){return Math.hypot(a.x-b.x,a.y-b.y)}

export default function App(){
 const [profile,setProfile]=useState<any>(()=>loadProfile()??{started:false,service:'POLICE',level:1,xp:0,money:100000,station:false,playerName:'Dispatcher'});
 const [screen,setScreen]=useState<Screen>(()=>loadProfile()?.started?'GAME':'MENU');
 const [game,setGame]=useState<GameState>(()=>cloneState()); const [connected,setConnected]=useState(false); const [service,setService]=useState<Service>(()=>loadProfile()?.service??'POLICE');
 const [role,setRole]=useState<Role>('CALL_TAKER'); const [tab,setTab]=useState<Tab>('CAD'); const [selected,setSelected]=useState('INC-1042'); const [filter,setFilter]=useState<'ALL'|Service>('ALL'); const [zoom,setZoom]=useState(1); const [notice,setNotice]=useState('');
 const currentService=profile.service as Service; const rank=ranks[currentService][Math.min(8,Math.max(0,profile.level-1))];
 const active=game.incidents.filter(i=>i.status!=='COMPLETE'&&i.status!=='CANCELLED'); const incident=game.incidents.find(i=>i.id===selected)??active[0];
 const myUnits:Unit[]=profile.station?game.units.filter(u=>u.service===currentService):[];
 function send(m:unknown){if(ws?.readyState===WebSocket.OPEN){ws.send(JSON.stringify(m));return true}return false}
 useEffect(()=>{if(screen!=='GAME')return;try{ws=new WebSocket(serverUrl);ws.onopen=()=>{setConnected(true);ws?.send(JSON.stringify({type:'HELLO',name:profile.playerName,role,token}))};ws.onclose=()=>{setConnected(false);ws=null};ws.onerror=()=>setConnected(false);ws.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.type==='STATE_SNAPSHOT'&&m.payload)setGame(m.payload);if(m.type==='ERROR')setNotice(m.message??'Server error')}catch{setNotice('Ungültige Serverantwort')}}}catch{setConnected(false)}return()=>{ws?.close();ws=null}},[screen]);
 useEffect(()=>{if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type:'HELLO',name:profile.playerName,role,token}))},[role]);
 useEffect(()=>{const t=setInterval(()=>setGame(s=>{const n=structuredClone(s);n.serverTime=Date.now();n.simulationMinutes=(n.simulationMinutes+1)%1440;n.world.hour=Math.floor(n.simulationMinutes/60);n.world.minute=n.simulationMinutes%60;return n}),1000);return()=>clearInterval(t)},[]);
 function start(s:Service){const p={...profile,started:true,service:s,level:1,xp:0,money:100000,station:false};setProfile(p);persist(p);setService(s);setScreen('GAME');setTab('AGENCY')}
 function build(){if(profile.station)return;const p={...profile,station:true,money:25000,xp:100};setProfile(p);persist(p);send({type:'BUILD_FACILITY',service:currentService,name:`${meta[currentService].name} Station`,position:{x:45+Math.random()*10,y:45+Math.random()*10}});setNotice(`${meta[currentService].station} gebaut. Deine Karriere beginnt als ${rank}.`)}
 function reward(){const xp=profile.xp+100;const p={...profile,xp,money:profile.money+500,level:Math.min(9,1+Math.floor(xp/500))};setProfile(p);persist(p)}
 function dispatch(u:Unit){if(!incident||u.status!=='AVAILABLE')return;if(send({type:'DISPATCH',unitId:u.id,incidentId:incident.id}))return;setGame(s=>{const n=structuredClone(s),i=n.incidents.find(x=>x.id===incident.id),v=n.units.find(x=>x.id===u.id);if(!i||!v)return s;i.status='RESPONDING';i.unitIds=[...new Set([...i.unitIds,u.id])];v.status='EN_ROUTE';v.target=i.location;return n})}
 function auto(){const u=myUnits.filter(u=>u.status==='AVAILABLE').sort((a,b)=>incident?dist(a.position,incident.location)-dist(b.position,incident.location):0)[0];if(u)dispatch(u);else setNotice('Keine verfügbare eigene Einheit.')}
 function complete(){if(!incident)return;if(send({type:'COMPLETE',incidentId:incident.id}))return;setGame(s=>{const n=structuredClone(s),i=n.incidents.find(x=>x.id===incident.id);if(!i)return s;i.status='COMPLETE';return n});reward()}
 function generate(){if(!send({type:'GENERATE_INCIDENT'}))setNotice('Der 911-Generator benötigt den Multiplayer-Server.')}
 function backMenu(){setScreen('MENU')}
 if(screen==='MENU')return <main className="rebuild-menu"><div className="menu-grid"/><section className="menu-content"><div className="menu-kicker"><i/>LIVE PUBLIC SAFETY SIMULATION</div><h1>AMERICAN<br/><strong>DISPATCH</strong></h1><p>Multiplayer 911 management · real-world map · build your own public safety agency</p><button className="hero-button" onClick={()=>setScreen('SERVICE')}>PLAY <span>→</span></button><button className="menu-secondary" onClick={()=>setNotice('Profilverwaltung folgt im nächsten Ausbau.')}>PROFILE / SETTINGS</button><div className="menu-status"><span><i/>SERVER READY</span><span>REDWOOD METRO · USA</span><span>BUILD 2.0</span></div>{notice&&<div className="toast">{notice}</div>}</section><footer>MAP DATA © OPENSTREETMAP CONTRIBUTORS · OPENFREEMAP</footer></main>;
 if(screen==='SERVICE')return <main className="service-screen"><header><button onClick={backMenu}>← BACK</button><div><small>NEW MULTIPLAYER SESSION</small><b>Choose your first agency</b></div><span className="server-pill"><i className={connected?'on':''}/>{connected?'ONLINE':'CONNECTING'}</span></header><section className="service-content"><div className="service-intro"><small>STARTING AT LEVEL 1</small><h2>BUILD YOUR AGENCY</h2><p>You start at zero. Choose one public-safety discipline. Rank, money, fleet and capabilities grow with your career.</p></div><div className="service-cards">{(['POLICE','FIRE','EMS'] as Service[]).map(s=><button key={s} className={`service-card ${s.toLowerCase()}`} onClick={()=>start(s)}><strong>{s}</strong><h3>{meta[s].name}</h3><p>Start with a {meta[s].station}. Unlock vehicles, personnel and specialist operations through American-style ranks.</p><small>LEVEL 1 · {ranks[s][0].toUpperCase()}</small><b>SELECT AGENCY →</b></button>)}</div><div className="service-note">SHARED WORLD · OTHER PLAYERS' FACILITIES REMAIN VISIBLE · YOUR PROGRESS IS YOUR OWN</div></section></main>;
 return <main className="rebuild-game"><header className="game-top"><button className="brand-mini" onClick={backMenu}><span>911</span><b>AMERICAN DISPATCH</b></button><div className="agency"><strong>{meta[currentService].name}</strong><small>{rank.toUpperCase()} · LEVEL {profile.level}</small></div><div className="top-stats"><span><small>XP</small><b>{profile.xp % 500}/500</b></span><span><small>BUDGET</small><b>{cash(profile.money)}</b></span><span><small>911</small><b>{game.statistics.calls}</b></span><span><small>SERVER</small><b className={connected?'online':'offline'}>{connected?'ONLINE':'OFFLINE'}</b></span></div></header><nav className="game-tabs">{(['CAD','AGENCY','RANKS','WORLD'] as Tab[]).map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}<select value={role} onChange={e=>setRole(e.target.value as Role)}>{Object.entries(roles).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></nav>
 {tab==='CAD'&&<section className="cad-grid"><aside className="cad-panel calls"><div className="panel-title"><span>911 CALL QUEUE</span><b>{active.length}</b></div><div className="filter-row"><button className={filter==='ALL'?'active':''} onClick={()=>setFilter('ALL')}>ALL</button>{(['POLICE','FIRE','EMS'] as Service[]).map(s=><button key={s} className={filter===s?'active':''} onClick={()=>setFilter(s)}>{s}</button>)}</div><div className="call-list">{active.filter(i=>filter==='ALL'||i.requiredServices.includes(filter)).map(i=><button key={i.id} className={selected===i.id?'call selected':'call'} onClick={()=>setSelected(i.id)}><strong>{i.id}</strong><span>P{i.priority} · {i.type}</span><small>{i.address}</small><em>{i.summary}</em><label>{getIncidentStatusLabel(i.status)}</label></button>)}</div><button className="dispatch-new" onClick={generate}>＋ GENERATE 911 CALL</button></aside><div className="map-stage"><RealMapView state={game} zoom={zoom} onZoomChange={setZoom} onIncidentSelect={setSelected}/><div className="map-banner"><b>{currentService} DISPATCH</b><span>{rank} · LEVEL {profile.level}</span><span>{game.world.traffic}% TRAFFIC</span></div></div><aside className="cad-panel units"><div className="panel-title"><span>YOUR UNITS</span><b>{myUnits.length}</b></div>{!profile.station?<div className="locked"><strong>NO STATION</strong><p>Build your first {meta[currentService].station} to unlock your fleet.</p><button onClick={()=>setTab('AGENCY')}>BUILD AGENCY</button></div>:<>{myUnits.map(u=><button className="unit-row" key={u.id} onClick={()=>dispatch(u)}><span className={`unit-dot ${u.service.toLowerCase()}`}/><div><b>{u.callsign}</b><small>{u.vehicleModel??u.type}</small></div><em>{u.status}</em></button>)}<button className="auto" onClick={auto}>AUTO DISPATCH</button></>}<div className="selected-actions">{incident&&<><strong>{incident.id}</strong><span>{incident.objective}</span><button onClick={complete}>COMPLETE INCIDENT</button></>}</div></aside></section>}
 {tab==='AGENCY'&&<section className="agency-page"><div className="agency-card"><small>YOUR ORGANIZATION</small><h2>{meta[currentService].name}</h2><div className="rank-display"><b>LEVEL {profile.level}</b><strong>{rank}</strong><span>{profile.xp} XP · {cash(profile.money)}</span></div>{!profile.station?<><p>You begin with no station, no fleet and no established agency. Your first purchase defines your operation.</p><button className="build" onClick={build}>BUILD {meta[currentService].station.toUpperCase()} · $75,000</button></>:<div className="built"><i>✓</i><div><b>{meta[currentService].station} operational</b><span>Shared-world headquarters · Fleet unlocked</span></div></div>}</div><div className="unlock-card"><small>UNLOCK ROADMAP</small>{ranks[currentService].map((r,i)=><div key={r} className={i<profile.level?'unlocked':''}><b>{i+1}</b><span>{r}</span><small>{i<profile.level?'UNLOCKED':i===profile.level?'NEXT':'LOCKED'}</small></div>)}</div></section>}
 {tab==='RANKS'&&<section className="ranks-page"><div><small>CAREER PROGRESSION</small><h2>YOUR RANKS</h2><p>American public-safety style rank progression. Each level controls what your agency can unlock.</p></div><div className="rank-grid">{ranks[currentService].map((r,i)=><article className={i<profile.level?'current':''} key={r}><small>LEVEL {i+1}</small><h3>{r}</h3><p>{i<2?'Frontline operations':i<4?'Core operations and fleet':i<6?'Supervision and expansion':i<8?'Special operations and management':'Executive command'}</p></article>)}</div></section>}
 {tab==='WORLD'&&<section className="world-page"><div><small>MULTIPLAYER WORLD</small><h2>REDWOOD METRO</h2><p>The map is a real OpenStreetMap-derived vector basemap rendered through MapLibre/OpenFreeMap. Your agency exists inside one shared world with other players.</p></div><div className="world-stats"><b>{game.facilities?.length??0}<small>FACILITIES</small></b><b>{game.units.length}<small>VISIBLE UNITS</small></b><b>{active.length}<small>ACTIVE 911</small></b><b>{game.world.population.toLocaleString('en-US')}<small>POPULATION</small></b></div></section>}
 {notice&&<div className="toast game-toast">{notice}<button onClick={()=>setNotice('')}>×</button></div>}</main>;
}
